# CDV Phylodynamics — Dataset Exploration

Interactive companion to the pipeline scripts. This notebook **imports** the functions
from `scripts/` rather than copying them, so there is one source of truth. Fix a bug in
a script and this notebook picks it up on the next restart.

Use it for the parts that need your eyes: reviewing ambiguous records, deciding scope,
and checking that the dataset can actually support the analysis.

**Order of operations**
1. Run the fetch and curation scripts (cells below, or from the terminal)
2. Explore what came back
3. Work the `needs_review` loop until it's clean
4. Make the scope decision at the Week 3 gate
5. Hand off to alignment and tree building

> The pipeline itself lives in `scripts/`. Don't paste analysis code here permanently —
> if you write something worth keeping, move it into a script so it stays reproducible.

## Setup

**Run this section first.** Every later cell depends on the imports and on `ROOT` being
set here. If you see `NameError: name 'os' is not defined` or similar, the kernel was
restarted and this cell needs re-running — *Kernel → Restart Kernel and Run All Cells*
is the reliable way back.

In [1]:
import os, sys, subprocess, importlib.util
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

# Optional override. Leave as None — the cell finds the repo on its own.
REPO_ROOT = None

MARKER = Path("scripts") / "02_curate_metadata.py"

def find_repo_root(explicit=None):
    # 1. explicit override
    if explicit is not None:
        cand = Path(explicit).expanduser().resolve()
        if (cand / MARKER).is_file():
            return cand
        raise FileNotFoundError(f"REPO_ROOT is set to {cand} but {MARKER} isn't there.")

    # 2. cwd and its parents (covers notebook at repo root or in notebooks/)
    cwd = Path.cwd().resolve()
    for cand in [cwd, *cwd.parents]:
        if (cand / MARKER).is_file():
            return cand

    # 3. last resort: search the home directory for it
    home = Path.home()
    hits = [p.parent.parent for p in home.rglob(str(MARKER)) if ".ipynb_checkpoints" not in str(p)]
    hits = sorted(set(hits))
    if len(hits) == 1:
        print(f"note: repo wasn't near the notebook; found it at {hits[0]}")
        return hits[0]
    if len(hits) > 1:
        raise FileNotFoundError(
            "Found more than one copy of the repo. Set REPO_ROOT to the one you want:\n"
            + "\n".join(f'    REPO_ROOT = Path("{h}")' for h in hits)
        )

    # nothing anywhere — say exactly what's wrong and what's on disk
    listing = sorted(p.name for p in cwd.iterdir())[:25] if cwd.is_dir() else []
    raise FileNotFoundError(
        f"Couldn't find scripts/02_curate_metadata.py anywhere under {home}.\n\n"
        f"cwd is {cwd}\n"
        f"cwd contains: {listing}\n\n"
        "The repo folder probably wasn't uploaded, or was uploaded flattened.\n"
        "Expected layout:\n"
        "    <repo>/scripts/    01_fetch_sequences.py, 02_curate_metadata.py, 03_align_and_tree.py\n"
        "    <repo>/config/     host_groups.tsv, vaccine_strains.txt\n"
        "    <repo>/notebooks/  this notebook\n\n"
        "Easiest fix: upload cdv-phylodynamics.zip and run in a cell:\n"
        "    import zipfile, pathlib\n"
        "    zipfile.ZipFile('cdv-phylodynamics.zip').extractall(pathlib.Path.home())"
    )

ROOT = find_repo_root(REPO_ROOT)
os.chdir(ROOT)
sys.path.insert(0, str(ROOT / "scripts"))
print("repo root:", ROOT)
print("scripts  :", sorted(p.name for p in (ROOT / "scripts").glob("*.py")))

pd.set_option("display.max_columns", 60)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 70)

plt.rcParams.update({
    "figure.dpi": 110, "font.size": 9, "axes.grid": True,
    "grid.alpha": 0.25, "axes.spines.top": False, "axes.spines.right": False,
})

RAW, INTERIM, PROCESSED = Path("data/raw"), Path("data/interim"), Path("data/processed")

repo root: /Users/batyanightingale/projects/cdv-phylodynamics
scripts  : ['01_fetch_sequences.py', '02_curate_metadata.py', '03_align_and_tree.py']

In [2]:
# Import the curation module so we can reuse its parsers interactively.
def load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

curate = load_module("curate", ROOT / "scripts" / "02_curate_metadata.py")

# Sanity check that the date parser behaves — cheap insurance against a silent regression
for raw in ["2013", "Aug-2013", "14-Aug-2013", "2013-08-14", "2011/2013", "unknown"]:
    iso, dec, prec = curate.parse_collection_date(raw)
    print(f"{raw:<14} -> {str(dec):<12} ({prec})")

2013           -> 2013.5       (year)
Aug-2013       -> 2013.6219178082192 (month)
14-Aug-2013    -> 2013.6164383561643 (day)
2013-08-14     -> 2013.6164383561643 (day)
2011/2013      -> 2012.5       (range)
unknown        -> None         (none)

## Step 1 — Fetch from GenBank

Needs your email; the API key is read from the `NCBI_API_KEY` environment variable.
Start with a dry run to see how many records match before downloading anything.

In [3]:
# Your email. NCBI requires it and will contact you before blocking. Fine to keep here.
EMAIL = "batya.nightingale@gmail.com"          # <-- put your address here

# API key: read from the environment if present, otherwise prompt.
# Either way it is never written into this notebook file.
# On JupyterHub, environment variables usually aren't set, so you'll get a prompt.
# The key lives in memory for this kernel session only — re-enter after a restart.
import getpass

API_KEY = os.environ.get("NCBI_API_KEY", "")
if not API_KEY:
    API_KEY = getpass.getpass("NCBI API key (leave blank to skip): ").strip()
    if API_KEY:
        os.environ["NCBI_API_KEY"] = API_KEY   # so the subprocess scripts see it

assert EMAIL and EMAIL != "you@example.com", "Set EMAIL above before fetching."
print("email  :", EMAIL)
print("api key:", f"set ({len(API_KEY)} chars), 10 req/s" if API_KEY
      else "not set, 3 req/s")


def run_script(script, *args):
    cmd = [sys.executable, f"scripts/{script}", *map(str, args)]
    print("$", " ".join(cmd), "\n")
    proc = subprocess.run(cmd, capture_output=True, text=True)
    print(proc.stdout or proc.stderr)
    return proc.returncode


run_script("01_fetch_sequences.py", "--email", EMAIL, "--dry-run")

NCBI API key (leave blank to skip):  ········

email  : batya.nightingale@gmail.com
api key: set (36 chars), 10 req/s
$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/01_fetch_sequences.py --email batya.nightingale@gmail.com --dry-run

2026-08-26 19:01:15,263  INFO     using NCBI API key (10 req/s)
2026-08-26 19:01:15,263  INFO     query: txid11232[Organism:exp] AND 200:20000[Sequence Length] NOT patent[Properties]
2026-08-26 19:01:16,513  INFO     matched 3818 records
2026-08-26 19:01:16,513  INFO     dry run — exiting without download

0

In [4]:
# Full download. Skips if today's file already exists.
run_script("01_fetch_sequences.py", "--email", EMAIL)

gb_files = sorted(RAW.glob("cdv_*.gb"))
print("\nGenBank files on disk:")
for f in gb_files:
    print(f"  {f}  ({f.stat().st_size/1e6:.1f} MB)")
GB = gb_files[-1] if gb_files else None
GB

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/01_fetch_sequences.py --email batya.nightingale@gmail.com

2026-08-26 19:01:34,208  INFO     using NCBI API key (10 req/s)
2026-08-26 19:01:34,208  INFO     query: txid11232[Organism:exp] AND 200:20000[Sequence Length] NOT patent[Properties]
2026-08-26 19:01:35,558  INFO     matched 3818 records
2026-08-26 19:01:38,890  INFO       200 / 3818 records
2026-08-26 19:01:40,134  INFO       400 / 3818 records
2026-08-26 19:01:41,714  INFO       600 / 3818 records
2026-08-26 19:01:43,990  INFO       800 / 3818 records
2026-08-26 19:01:44,974  INFO       1000 / 3818 records
2026-08-26 19:01:46,364  INFO       1200 / 3818 records
2026-08-26 19:01:51,288  INFO       1400 / 3818 records
2026-08-26 19:01:54,282  INFO       1600 / 3818 records
2026-08-26 19:01:56,398  INFO       1800 / 3818 records
2026-08-26 19:01:58,412  INFO       2000 / 3818 records
2026-08-26 19:02:00,755  INFO       2200 / 3818 records
2026-08-26 19:02:01,793  INFO       2400 / 3818 records
2026-08-26 19:02:04,396  INFO       2600 / 3818 records
2026-08-26 19:02:05,767  INFO       2800 / 3818 records
2026-08-26 19:02:07,451  INFO       3000 / 3818 records
2026-08-26 19:02:11,176  INFO       3200 / 3818 records
2026-08-26 19:02:12,946  INFO       3400 / 3818 records
2026-08-26 19:02:14,048  INFO       3600 / 3818 records
2026-08-26 19:02:16,650  INFO       3800 / 3818 records
2026-08-26 19:02:17,102  INFO       3818 / 3818 records
2026-08-26 19:02:17,303  INFO     wrote data/raw/cdv_20260826.gb (23.7 MB)
2026-08-26 19:02:17,303  INFO     wrote data/raw/cdv_20260826.acc (3818 accessions)
2026-08-26 19:02:17,303  INFO     done in 41.7 s


GenBank files on disk:
  data/raw/cdv_20260826.gb  (23.7 MB)

PosixPath('data/raw/cdv_20260826.gb')

## Step 2 — Curate

Parses records, normalizes hosts, flags vaccine strains, parses dates, extracts H sequences.
Re-run this freely — it's deterministic and cheap.

In [5]:
assert GB is not None, "No GenBank file found. Run the fetch cell first."
run_script("02_curate_metadata.py", "--gb", GB)

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/02_curate_metadata.py --gb data/raw/cdv_20260826.gb

2026-08-26 19:02:17,767  INFO     loaded 32 vaccine patterns, 101 host patterns
2026-08-26 19:02:19,357  INFO     parsed 3818 records
2026-08-26 19:02:19,359  INFO     excluded 88 vaccine / vaccine-derived records
2026-08-26 19:02:19,360  INFO     excluded 1350 records without an identifiable H sequence
2026-08-26 19:02:19,361  INFO     excluded 69 records with H shorter than 400 nt
2026-08-26 19:02:19,361  INFO     excluded 0 records with implausibly long H (annotation problem)
2026-08-26 19:02:19,362  INFO     excluded 412 records without a usable collection date
2026-08-26 19:02:19,363  INFO     excluded 138 records with unresolved host
2026-08-26 19:02:19,453  INFO     --------------------------------------------------------------
2026-08-26 19:02:19,453  INFO     RETAINED: 1761 of 3818 records
2026-08-26 19:02:19,453  INFO     H sequences written: 1761   (all-locus: 1761)
2026-08-26 19:02:19,453  INFO
2026-08-26 19:02:19,453  INFO     By host group:
2026-08-26 19:02:19,454  INFO         domestic_dog       915
2026-08-26 19:02:19,454  INFO         wild_canid         386
2026-08-26 19:02:19,454  INFO         mustelid           203
2026-08-26 19:02:19,454  INFO         procyonid          144
2026-08-26 19:02:19,454  INFO         wild_felid          63
2026-08-26 19:02:19,454  INFO         other               16
2026-08-26 19:02:19,454  INFO         ailurid              9
2026-08-26 19:02:19,454  INFO         pinniped             8
2026-08-26 19:02:19,454  INFO         primate              7
2026-08-26 19:02:19,454  INFO         viverrid             6
2026-08-26 19:02:19,454  INFO         ursid                4
2026-08-26 19:02:19,454  INFO
2026-08-26 19:02:19,454  INFO     By date precision:
2026-08-26 19:02:19,455  INFO         year               951
2026-08-26 19:02:19,455  INFO         day                523
2026-08-26 19:02:19,455  INFO         month              222
2026-08-26 19:02:19,455  INFO         range               65
2026-08-26 19:02:19,455  INFO
2026-08-26 19:02:19,455  INFO     Date range: 1982.11 – 2026.50
2026-08-26 19:02:19,456  INFO     Countries represented: 49
2026-08-26 19:02:19,456  INFO
2026-08-26 19:02:19,456  INFO     NEEDS HUMAN REVIEW: 291 records -> data/interim/needs_review.tsv
2026-08-26 19:02:19,456  INFO     --------------------------------------------------------------
2026-08-26 19:02:19,456  INFO
2026-08-26 19:02:19,456  INFO     NEXT: open needs_review.tsv. For each ambiguous host, either add a
2026-08-26 19:02:19,456  INFO     pattern to config/host_groups.tsv or confirm the record should be
2026-08-26 19:02:19,456  INFO     dropped. Then re-run this script. Repeat until the file is empty or
2026-08-26 19:02:19,456  INFO     everything left is genuinely unusable.

0

In [6]:
all_df   = pd.read_csv(INTERIM / "metadata_all.tsv", sep="\t")
clean    = pd.read_csv(PROCESSED / "metadata_clean.tsv", sep="\t")
excluded = pd.read_csv(INTERIM / "exclusions.tsv", sep="\t")
review   = pd.read_csv(INTERIM / "needs_review.tsv", sep="\t")

print(f"parsed   {len(all_df):>6}")
print(f"retained {len(clean):>6}  ({len(clean)/len(all_df):.0%})")
print(f"excluded {len(excluded):>6}")
print(f"review   {len(review):>6}")

parsed     3818
retained   1761  (46%)
excluded   2057
review      291

### Why records were excluded

This table is part of your methods section. Every number here needs a defensible reason.

In [7]:
(excluded["exclude_reason"].value_counts()
 .rename_axis("reason").reset_index(name="n")
 .assign(pct=lambda d: (100 * d.n / len(all_df)).round(1)))

                         reason     n   pct
0            no_H_gene_sequence  1350  35.4
1  no_parseable_collection_date   412  10.8
2               host_unresolved   138   3.6
3    vaccine_or_vaccine_derived    88   2.3
4          H_shorter_than_400nt    69   1.8

## Step 3 — The `needs_review` loop

**This is the part that can't be automated.** For each ambiguous record: either add a
pattern to `config/host_groups.tsv`, or accept that it should be dropped.

The helper below lists every host string that failed to match, with counts, so you can
prioritise. A string appearing 40 times is worth a pattern; one appearing once may not be.

In [8]:
def unmatched_hosts(df):
    """Host strings that didn't match any pattern, most frequent first."""
    u = df[df["host_ambiguous"] & df["host_raw"].notna() & (df["host_raw"].str.strip() != "")]
    return (u["host_raw"].str.strip().value_counts()
            .rename_axis("host_raw").reset_index(name="n"))

unmatched_hosts(all_df).head(40)

                                          host_raw   n
0                           Canis_lupus_familiaris  39
1                       Paradoxurus hermaphroditus  25
2                                            Canis  19
3                                            urine  10
4                            Tamandua tetradactyla  10
5                                  Cerdocyun thous   8
6                                        Canis sp.   8
7   Callithrix penicillata (Black-tufted marmoset)   7
8                                          Vaccine   7
9               nasal swab and anticoagulant-blood   7
10                                   Neogale vison   6
11                                         vaccine   6
12                          Callithrix penicillata   6
13                                      carnivores   6
14                                     Felis rufus   5
15                                           blood   5
16                         Myrmecophaga tridactyla   4
17                                    lesser panda   3
18                               Otocyon megalotis   3
19                               Mephitis mephitis   3
20                                  Canis simensis   3
21                                 Canis mesomelas   3
22        Myrmecophaga tridactyla (Giant anteater)   3
23                           Sciurus variegatoides   2
24                               Coendou mexicanus   2
25                                    swab of anus   2
26                           Chrysocyon brachyurus   2
27                              Parahyaena brunnea   2
28                                    Pusa caspica   2
29       Coregonus autumnalis migratorius (Georgi)   2
30      Cottocomephorus grewingki (Dybowski, 1874)   2
31            urine and urinary bladder epithelium   2
32                              Limnea auricularia   2
33                             Lymnaea auricularia   2
34                      Epischura baicalensis Sars   2
35                                          jackel   2
36                          Arctocephalus forsteri   2
37                                  German spaniel   2
38                                       Vaccine B   2
39                       conjunctival swab isolate   2

In [9]:
def test_pattern(pattern, df=None):
    """Preview what a candidate pattern would match BEFORE adding it to the config.

    Watch for over-matching: 'dog' matches 'raccoon dog', which is why order
    matters in host_groups.tsv. Check this output for surprises.
    """
    df = all_df if df is None else df
    hits = df[df["host_raw"].fillna("").str.lower().str.contains(pattern.lower(), regex=False)]
    print(f"'{pattern}' matches {len(hits)} records\n")
    return hits["host_raw"].value_counts().rename_axis("host_raw").reset_index(name="n")

test_pattern("fox")

'fox' matches 258 records

                               host_raw    n
0                                   fox  184
1                               red fox   16
2               Red fox (Vulpes vulpes)   11
3   Urocyon cinereoargenteus (gray fox)   11
4                          Arctic foxes    9
5                              Gray fox    5
6                                   Fox    4
7   Urocyon cinereoargenteus (grey fox)    4
8                         bat-eared fox    4
9                             fox brain    2
10                           arctic fox    1
11   Lycalopex gymnocercus (Pampas fox)    1
12                          Fox terrier    1
13    Cerdocyon thous (crab-eating fox)    1
14                        dog breed Fox    1
15                 Vulpes lagopus (fox)    1
16                           Arctic fox    1
17              Vulpes vulpes (red fox)    1

### Ambiguous dates

Dates the parser couldn't read. Some are genuinely unusable (`unknown`, `NA`); others are
formats worth adding to `parse_collection_date()` in the curation script.

In [11]:
bad_dates = all_df[all_df["decimal_year"].isna() & all_df["collection_date_raw"].notna()]
bad_dates["collection_date_raw"].value_counts().head(25)

Series([], Name: count, dtype: int64)

### Partial H sequences found by length heuristic

These were identified by sequence length rather than annotation, so they're less certain.
Currently retained and flagged. Decide whether to keep them — more data versus more noise.

In [12]:
heur = all_df[all_df["H_source"].astype(str).str.startswith("length_heuristic")]
print(f"{len(heur)} records found by heuristic")
heur[["accession", "description", "length", "H_length", "H_source", "host_group"]].head(20)

38 records found by heuristic

       accession                                                            description  length  H_length                  H_source    host_group
183   PX224982.1  UNVERIFIED: Morbillivirus canis isolate TR-5/ similar to H protein...    1188      1188  length_heuristic_partial  domestic_dog
184   PX224981.1  UNVERIFIED: Morbillivirus canis isolate TR-18/ similar to H protei...    1188      1188  length_heuristic_partial  domestic_dog
699   OR529789.1  Morbillivirus canis isolate Q22 nonfunctional hemagglutinin gene, ...    1824      1824     length_heuristic_full    wild_canid
1443  MT773247.1  Canine morbillivirus isolate N90 hemagglutinin protein H (gp6) gen...     738       738  length_heuristic_partial  domestic_dog
1444  MT773246.1  Canine morbillivirus isolate N62 hemagglutinin protein H (gp6) gen...     738       738  length_heuristic_partial  domestic_dog
1445  MT773245.1  Canine morbillivirus isolate N584 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1446  MT773244.1  Canine morbillivirus isolate N554 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1447  MT773243.1  Canine morbillivirus isolate N513 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1448  MT773242.1  Canine morbillivirus isolate N481 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1449  MT773241.1  Canine morbillivirus isolate N473 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1450  MT773240.1  Canine morbillivirus isolate N469 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1451  MT773239.1  Canine morbillivirus isolate N467 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1452  MT773238.1  Canine morbillivirus isolate N466 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1453  MT773237.1  Canine morbillivirus isolate N464 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1454  MT773236.1  Canine morbillivirus isolate N455 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1455  MT773235.1  Canine morbillivirus isolate N435 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1456  MT773234.1  Canine morbillivirus isolate N434 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1457  MT773233.1  Canine morbillivirus isolate N423 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1458  MT773232.1  Canine morbillivirus isolate N400 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog
1459  MT773231.1  Canine morbillivirus isolate N394 hemagglutinin protein H (gp6) ge...     738       738  length_heuristic_partial  domestic_dog

---
## Step 4 — The Week 3 gate

The decision: is there enough signal across enough hosts to run the analysis as scoped,
or does it need narrowing to felids only, or to one region?

In [ ]:
summary = (clean.groupby("host_group")
           .agg(n=("accession", "size"),
                earliest=("decimal_year", "min"),
                latest=("decimal_year", "max"),
                countries=("country", "nunique"),
                day_precision=("date_precision", lambda s: (s == "day").sum()))
           .sort_values("n", ascending=False))
summary["span_yrs"] = (summary["latest"] - summary["earliest"]).round(1)
summary.round(2)

In [ ]:
fig, axes = plt.subplots(2, 2, figsize=(11, 7.5))

# host group composition
s = clean["host_group"].value_counts()
axes[0,0].barh(s.index[::-1], s.values[::-1], color="#4B3A79")
axes[0,0].set_title("Sequences per host group")
axes[0,0].axvline(5, color="#C0697F", ls="--", lw=1)
axes[0,0].text(5, -0.4, " n=5 floor", color="#C0697F", fontsize=8, va="top")

# sampling through time by host
for grp, sub in clean.groupby("host_group"):
    axes[0,1].scatter(sub["decimal_year"], [grp]*len(sub), s=9, alpha=0.55)
axes[0,1].set_title("Sampling through time")
axes[0,1].set_xlabel("year")

# date precision
p = clean["date_precision"].value_counts()
axes[1,0].bar(p.index, p.values, color="#6E5CA0")
axes[1,0].set_title("Date precision")

# sequences per year
yr = clean["decimal_year"].astype(int).value_counts().sort_index()
axes[1,1].bar(yr.index, yr.values, color="#4B3A79", width=0.85)
axes[1,1].set_title("Sequences per year")

plt.tight_layout()
plt.show()

**How to read these**

- **Host group counts** — the dashed line is a rough floor of 5. Groups below it can't
  support discrete trait analysis and should be merged or dropped.
- **Sampling through time** — you need temporal *spread* within groups, not just totals.
  A wild felid group where every sequence is from 2010–2012 gives BEAST almost nothing.
- **Date precision** — year-only dates are usable but add uncertainty. If most tips are
  year-only, mention it as a limitation.
- **Sequences per year** — heavy recent skew is normal and fine; a gap of a decade is not.

In [13]:
# The explicit gate check
WILD = ["wild_felid", "wild_canid", "mustelid", "procyonid", "pinniped", "ursid", "ailurid", "viverrid"]
wild = clean[clean["host_group"].isin(WILD)]

print(f"wild carnivore sequences with host + date : {len(wild)}")
print(f"distinct wild host groups (n>=5)          : {(wild['host_group'].value_counts() >= 5).sum()}")
print(f"temporal span of wild sequences           : "
      f"{wild['decimal_year'].min():.1f} - {wild['decimal_year'].max():.1f}")
print(f"domestic dog sequences                    : {(clean['host_group']=='domestic_dog').sum()}")
print()
n = len(wild)
if n >= 150:
    print("=> Comfortable. Proceed with the full cross-host analysis.")
elif n >= 60:
    print("=> Workable. Consider merging the thinner host groups.")
else:
    print("=> Thin. Narrow the scope: felids only, or one geographic region.")
    print("   Send these numbers over and we'll pick the cut together.")

wild carnivore sequences with host + date : 823
distinct wild host groups (n>=5)          : 7
temporal span of wild sequences           : 1988.5 - 2026.5
domestic dog sequences                    : 915

=> Comfortable. Proceed with the full cross-host analysis.

## Step 5 — Hand off to alignment

Once `needs_review` is worked through and the gate passes, relabel and align. The script
deliberately stops after alignment so you look at it before spending compute on a tree.

In [14]:
run_script("03_align_and_tree.py",
           "--fasta", "data/processed/sequences_H.fasta",
           "--metadata", "data/processed/metadata_clean.tsv",
           "--stop-after", "align")

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/03_align_and_tree.py --fasta data/processed/sequences_H.fasta --metadata data/processed/metadata_clean.tsv --stop-after align

2026-08-26 19:05:06,075  INFO     1761 sequences, 1761 metadata rows
2026-08-26 19:05:06,096  INFO     wrote data/processed/H_labelled.fasta (1761 sequences)
2026-08-26 19:05:06,097  INFO     wrote data/processed/H_dates.tsv
2026-08-26 19:05:06,098  INFO     host composition of the alignment set:
2026-08-26 19:05:06,098  INFO         domestic_dog       915
2026-08-26 19:05:06,098  INFO         wild_canid         386
2026-08-26 19:05:06,098  INFO         mustelid           203
2026-08-26 19:05:06,098  INFO         procyonid          144
2026-08-26 19:05:06,098  INFO         wild_felid          63
2026-08-26 19:05:06,098  INFO         other               16
2026-08-26 19:05:06,098  INFO         ailurid              9
2026-08-26 19:05:06,098  INFO         pinniped             8
2026-08-26 19:05:06,098  INFO         primate              7
2026-08-26 19:05:06,098  INFO         viverrid             6
2026-08-26 19:05:06,098  INFO         ursid                4
2026-08-26 19:05:06,098  WARNING  host groups with <5 sequences: ursid
2026-08-26 19:05:06,098  WARNING    discrete trait analysis will be unreliable for these. Consider merging them into a broader category or excluding them.
2026-08-26 19:05:06,099  INFO     aligning with MAFFT (auto)...
2026-08-26 19:05:36,588  INFO     wrote data/processed/H_aligned.fasta
2026-08-26 19:05:36,609  INFO
2026-08-26 19:05:36,609  INFO     >>> STOP AND LOOK AT THE ALIGNMENT before building a tree.
2026-08-26 19:05:36,609  INFO     >>> Open data/processed/H_aligned.fasta in AliView or Jalview. Check the ends, check for
2026-08-26 19:05:36,609  INFO     >>> frame shifts, check nothing is obviously misaligned.
2026-08-26 19:05:36,609  INFO

0

Open `data/processed/H_aligned.fasta` in **AliView** or **Jalview**. Look for ragged ends,
frame shifts, and any sequence that looks obviously misaligned. Then build the tree:

```bash
python scripts/03_align_and_tree.py \
    --fasta data/processed/sequences_H.fasta \
    --metadata data/processed/metadata_clean.tsv
```

### Then, in order

1. **Open the tree in FigTree.** Does the lineage structure look like published CDV phylogenies?
2. **Find the vaccine clade.** Any "field isolate" sitting inside it is a mislabelled vaccine
   sequence the name filter missed. Add it to `config/vaccine_strains.txt` and re-run from step 2.
   *This check is not optional — name matching provably cannot catch every vaccine-derived sequence.*
3. **Reproduce a published phylogeny** before trusting anything novel.
4. **TempEst** with `H_ml.treefile` and `H_dates.tsv` — check the root-to-tip regression.
   Positive slope and reasonable R² means tip-dated BEAST analysis is viable.

In [16]:
run_script("03_align_and_tree.py",
           "--fasta", "data/processed/sequences_H.fasta",
           "--metadata", "data/processed/metadata_clean.tsv")

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/03_align_and_tree.py --fasta data/processed/sequences_H.fasta --metadata data/processed/metadata_clean.tsv

2026-08-26 19:15:57,733  INFO     1761 sequences, 1761 metadata rows
2026-08-26 19:15:57,752  INFO     wrote data/processed/H_labelled.fasta (1761 sequences)
2026-08-26 19:15:57,753  INFO     wrote data/processed/H_dates.tsv
2026-08-26 19:15:57,754  INFO     host composition of the alignment set:
2026-08-26 19:15:57,754  INFO         domestic_dog       915
2026-08-26 19:15:57,754  INFO         wild_canid         386
2026-08-26 19:15:57,754  INFO         mustelid           203
2026-08-26 19:15:57,754  INFO         procyonid          144
2026-08-26 19:15:57,754  INFO         wild_felid          63
2026-08-26 19:15:57,754  INFO         other               16
2026-08-26 19:15:57,754  INFO         ailurid              9
2026-08-26 19:15:57,754  INFO         pinniped             8
2026-08-26 19:15:57,754  INFO         primate              7
2026-08-26 19:15:57,754  INFO         viverrid             6
2026-08-26 19:15:57,754  INFO         ursid                4
2026-08-26 19:15:57,754  WARNING  host groups with <5 sequences: ursid
2026-08-26 19:15:57,754  WARNING    discrete trait analysis will be unreliable for these. Consider merging them into a broader category or excluding them.
2026-08-26 19:15:57,754  INFO     aligning with MAFFT (auto)...
2026-08-26 19:16:23,139  INFO     wrote data/processed/H_aligned.fasta
2026-08-26 19:16:23,158  INFO
2026-08-26 19:16:23,158  INFO     >>> STOP AND LOOK AT THE ALIGNMENT before building a tree.
2026-08-26 19:16:23,158  INFO     >>> Open data/processed/H_aligned.fasta in AliView or Jalview. Check the ends, check for
2026-08-26 19:16:23,158  INFO     >>> frame shifts, check nothing is obviously misaligned.
2026-08-26 19:16:23,158  INFO
2026-08-26 19:16:23,159  INFO     $ iqtree2 -s data/processed/H_aligned.fasta -m MFP -B 1000 --alrt 1000 -T AUTO --prefix data/processed/H_ml -redo
IQ-TREE multicore version 2.2.2.9 COVID-edition for Mac OS X 64-bit built Aug  6 2023
Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams, Ly Trong Nhan.

Host:    Batyas-MBP.lan (AVX2, FMA3, 16 GB RAM)
Command: iqtree2 -s data/processed/H_aligned.fasta -m MFP -B 1000 --alrt 1000 -T AUTO --prefix data/processed/H_ml -redo
Seed:    592693 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Wed Aug 26 19:16:23 2026
Kernel:  AVX+FMA - auto-detect threads (8 CPU cores detected)

Reading alignment file data/processed/H_aligned.fasta ... Fasta format detected
Reading fasta file: done in 0.056201 secs using 94.56% CPU
Alignment most likely contains DNA/RNA sequences
Constructing alignment: done in 0.0480359 secs using 700.5% CPU
WARNING: 1 sites contain only gaps or ambiguous characters.
Alignment has 1761 sequences with 1988 columns, 1819 distinct patterns
1380 parsimony-informative, 256 singleton sites, 352 constant sites
                                Gap/Ambiguity  Composition  p-value
Analyzing sequences: done in 0.00667095 secs using 701% CPU
   1  PZ769327|wild_canid|2025.500      8.25%    passed     97.87%
   2  PZ766579|wild_canid|2025.500     10.21%    passed     99.96%
   3  OP209186|mustelid|2018.932        8.25%    passed     99.55%
   4  OP209185|mustelid|2021.164        8.25%    passed     99.24%
   5  OK557797|wild_canid|2021.500      8.25%    passed     99.88%
   6  OK557796|wild_canid|2021.500      8.25%    passed     99.88%
   7  OK557787|wild_canid|2021.500      8.25%    passed     99.88%
   8  OK557785|wild_canid|2021.500      8.25%    passed     99.77%
   9  OK557788|wild_canid|2021.500      8.25%    passed     99.99%
  10  OK557783|wild_canid|2021.500      8.25%    passed     99.99%
  11  OK557781|wild_canid|2021.500      8.25%    passed     99.97%
  12  OK557795|wild_canid|2021.500      8.25%    passed     99.74%
  13  OK557793|wild_canid|2021.500      8.25%    passed     99.81%
  14  OK557792|wild_canid|2021.500      8.25%    passed     99.81%
  15  OK557791|wild_canid|2021.500      8.25%    passed     99.81%
  16  OK557790|wild_canid|2021.500      8.25%    passed     99.81%
  17  OK557789|wild_canid|2021.500      8.25%    passed     99.81%
  18  OK557786|wild_canid|2021.500      8.25%    passed     99.81%
  19  OK557784|wild_canid|2021.500      8.25%    passed     99.81%
  20  OK557782|wild_canid|2021.500      8.25%    passed     99.81%
  21  OK557780|wild_canid|2021.500      8.25%    passed     99.81%
  22  OK557779|wild_canid|2021.500      8.25%    passed     99.89%
  23  OK557794|wild_canid|2021.500      8.25%    passed     99.98%
  24  PZ766578|wild_canid|2024.500     10.21%    passed     98.17%
  25  PZ766577|wild_canid|2024.500     10.21%    passed     98.17%
  26  PZ766576|wild_canid|2024.500     10.21%    passed     98.17%
  27  PZ766575|wild_canid|2024.500     10.21%    passed     98.77%
  28  OP546527|wild_canid|2021.500      8.25%    passed     97.93%
  29  MW015090|mustelid|2018.500        8.25%    passed     99.60%
  30  MW015089|mustelid|2018.500        8.25%    passed     99.39%
  31  MN044701|wild_canid|2018.016     15.49%    passed     90.59%
  32  MN044697|domestic_dog|2018.260   17.00%    passed     85.15%
  33  MN044696|wild_canid|2017.682     14.94%    passed     93.12%
  34  MW036820|wild_canid|2019.500      8.25%    passed     98.26%
  35  MW036817|wild_canid|2018.500      8.25%    passed     97.20%
  36  MW036808|mustelid|2018.500        8.25%    passed     98.50%
  37  MW036782|mustelid|2019.500        8.25%    passed     97.96%
  38  MN044700|wild_canid|2018.151     14.44%    passed     89.30%
  39  MN044693|mustelid|2017.866       14.44%    passed     92.48%
  40  MN044688|wild_canid|2015.156     14.44%    passed     92.48%
  41  MN044686|wild_canid|2014.362     14.44%    passed     89.30%
  42  MN044694|wild_canid|2017.003     14.44%    passed     87.17%
  43  MN044692|mustelid|2017.874       15.49%    passed     89.40%
  44  MN044698|wild_canid|2018.016     14.29%    passed     94.51%
  45  MN044687|wild_canid|2014.082     14.29%    passed     92.26%
  46  MN044681|wild_canid|2013.400     14.34%    passed     91.22%
  47  MN044671|mustelid|2012.792       14.29%    passed     90.56%
  48  MN044672|mustelid|2012.792       14.29%    passed     92.26%
  49  MN044685|wild_canid|2014.033     14.34%    passed     89.27%
  50  MN044675|mustelid|2012.902       14.29%    passed     88.59%
  51  MN044674|mustelid|2012.866       14.34%    passed     92.41%
  52  MN044676|mustelid|2012.817       14.29%    passed     92.05%
  53  MN044670|wild_canid|2012.719     14.29%    passed     90.00%
  54  MN044663|wild_canid|2012.344     15.95%    passed     85.73%
  55  MN044662|wild_canid|2012.607     19.57%    passed     92.05%
  56  MN044668|wild_canid|2012.678     21.38%    passed     92.91%
  57  MN044684|wild_canid|2013.863     14.59%    passed     87.18%
  58  MN044677|wild_canid|2013.145     15.34%    passed     85.41%
  59  MN044699|wild_canid|2018.121     14.34%    passed     92.16%
  60  MN044695|wild_canid|2017.422     14.89%    passed     86.80%
  61  MN044691|wild_canid|2016.872     15.74%    passed     87.79%
  62  MN044690|wild_canid|2016.432     15.64%    passed     86.26%
  63  MN044689|mustelid|2016.262       15.69%    passed     86.68%
  64  MN044682|wild_canid|2013.518     15.29%    passed     86.53%
  65  MN044680|mustelid|2013.479       15.59%    passed     84.92%
  66  MN044669|wild_canid|2012.710     17.00%    passed     87.90%
  67  MN044666|mustelid|2012.628       16.90%    passed     87.54%
  68  MN044664|wild_canid|2012.585     17.81%    passed     90.30%
  69  MN044665|wild_canid|2012.590     17.30%    passed     87.23%
  70  MN044667|wild_canid|2012.620     20.17%    passed     87.86%
  71  PP683092|mustelid|2012.959        8.25%    passed     98.48%
  72  MN044683|wild_canid|2013.658     14.59%    passed     93.20%
  73  MN044678|mustelid|2013.285       15.69%    passed     85.20%
  74  MN044679|wild_canid|2013.375     14.34%    passed     89.66%
  75  MN044673|wild_canid|2012.866     14.29%    passed     88.78%
  76  PX610320|wild_canid|2015.500      2.11%    passed     97.14%
  77  PX610319|wild_felid|2020.500      2.11%    passed     96.16%
  78  OR161408|wild_felid|2020.500      8.25%    passed     99.50%
  79  OL795430|wild_canid|2016.500     10.41%    passed     99.64%
  80  MN267061|wild_canid|2016.500      8.25%    passed     99.83%
  81  OL795426|wild_canid|2015.500      8.25%    passed     99.67%
  82  MN267062|procyonid|2015.500       8.25%    passed     99.83%
  83  MN267060|procyonid|2015.500       8.25%    passed     99.86%
  84  OL795423|wild_canid|2016.500      8.25%    passed     99.94%
  85  OP209189|mustelid|2007.500        8.25%    passed     99.49%
  86  OM811640|mustelid|2006.893        8.25%    passed     99.32%
  87  KF430377|mustelid|2013.500        8.25%    passed     99.95%
  88  KF430364|mustelid|2012.500        8.25%    passed     99.95%
  89  KF430376|wild_canid|2013.500      8.25%    passed     99.95%
  90  KF430370|mustelid|2013.500        8.25%    passed     99.98%
  91  KF430345|mustelid|2012.500        8.25%    passed     99.98%
  92  KF430367|mustelid|2012.500        8.25%    passed     99.95%
  93  KF430359|wild_canid|2012.500      8.25%    passed     99.95%
  94  KF430346|wild_canid|2012.500      8.25%    passed     99.95%
  95  KF430343|mustelid|2012.500        8.25%    passed     99.95%
  96  KF430341|mustelid|2012.500        8.25%    passed     99.95%
  97  KF430363|mustelid|2011.500        8.25%    passed     99.85%
  98  KF430362|wild_canid|2012.500      8.25%    passed     99.85%
  99  KF430361|wild_canid|2012.500      8.25%    passed     99.85%
 100  KF430353|mustelid|2012.500        8.25%    passed     99.98%
 101  KF430357|wild_canid|2012.500      8.25%    passed     99.91%
 102  KF430344|mustelid|2012.500        8.25%    passed     99.80%
 103  KF430350|mustelid|2012.500        8.25%    passed     99.80%
 104  KF430348|mustelid|2012.500        8.25%    passed     99.80%
 105  KF430342|mustelid|2012.500        8.25%    passed     99.95%
 106  KF430365|mustelid|2012.500        8.25%    passed     99.84%
 107  KF430356|mustelid|2012.500        8.25%    passed     99.93%
 108  KF430369|wild_canid|2013.500      8.25%    passed     99.87%
 109  KF430358|wild_canid|2012.500      8.25%    passed     99.87%
 110  KF430354|mustelid|2012.500        8.25%    passed     99.87%
 111  KF430340|mustelid|2012.500        8.25%    passed     99.72%
 112  KF430355|mustelid|2012.500        8.25%    passed     99.85%
 113  KF430337|mustelid|2012.500        8.25%    passed     99.80%
 114  KF430338|mustelid|2012.500        8.25%    passed     99.57%
 115  KF430339|mustelid|2012.500        8.25%    passed     99.40%
 116  KF430352|mustelid|2012.500        8.25%    passed     99.82%
 117  KF430366|mustelid|2013.500        8.25%    passed     99.85%
 118  KF430368|mustelid|2013.500        8.25%    passed     99.85%
 119  KF430347|mustelid|2012.500        8.25%    passed     99.95%
 120  KF430360|wild_canid|2012.500      8.25%    passed     99.51%
 121  KF430351|mustelid|2012.500        8.25%    passed     99.42%
 122  KF430349|mustelid|2012.500        8.25%    passed     99.77%
 123  KF430375|mustelid|2013.500        8.25%    passed     99.81%
 124  JN153025|wild_canid|2008.500      8.25%    passed     99.89%
 125  JN153024|wild_canid|2008.500      8.25%    passed     99.93%
 126  PX734748|wild_canid|2009.500      8.25%    passed     99.52%
 127  PX734733|wild_canid|2010.500      8.25%    passed     99.52%
 128  HM120874|wild_canid|2009.500      8.25%    passed     99.52%
 129  JF810110|mustelid|2002.500        8.25%    passed     99.64%
 130  JF810108|wild_canid|2010.500      8.25%    passed     99.63%
 131  JF810106|wild_canid|2010.500      8.25%    passed     99.63%
 132  JF810111|domestic_dog|2010.500    8.25%    passed     99.40%
 133  JF810107|wild_canid|2010.500      8.25%    passed     99.40%
 134  JF810109|wild_felid|2010.500      8.25%    passed     99.19%
 135  FJ416339|wild_canid|2008.210      8.25%    passed     99.82%
 136  FJ416338|mustelid|2008.402        8.25%    passed     99.82%
 137  FJ416336|wild_canid|2008.175      8.25%    passed     99.82%
 138  FJ416337|wild_canid|2008.175      8.25%    passed     99.62%
 139  PX734745|wild_canid|2009.500      8.25%    passed     99.82%
 140  GQ214372|domestic_dog|2004.500   59.76%    passed     95.69%
 141  OL795424|wild_canid|2017.500      8.25%    passed     98.23%
 142  OL795429|wild_canid|2016.500      8.25%    passed     98.14%
 143  OL795427|wild_canid|2016.500      8.25%    passed     98.14%
 144  OL795422|wild_canid|2017.500      8.25%    passed     98.14%
 145  OL795421|wild_canid|2017.500      8.25%    passed     98.14%
 146  OL795425|wild_canid|2017.500      8.25%    passed     98.85%
 147  OL795428|wild_canid|2016.500      8.25%    passed     98.89%
 148  MW036800|wild_canid|2019.500      8.25%    passed     97.25%
 149  MW036798|wild_canid|2018.500      8.25%    passed     96.42%
 150  MW036781|mustelid|2019.500        8.25%    passed     94.11%
 151  MW036787|mustelid|2019.500        8.30%    passed     96.43%
 152  MW036777|wild_canid|2019.500      8.25%    passed     93.52%
 153  OP209188|mustelid|2020.915        8.25%    passed     99.81%
 154  MH430948|domestic_dog|2016.500    8.25%    passed     99.52%
 155  PX954424|wild_canid|2024.407      8.25%    passed     99.31%
 156  MW828751|wild_canid|2020.500     46.13%    passed     89.27%
 157  MW828750|wild_canid|2020.500     46.13%    passed     89.27%
 158  MW828749|mustelid|2016.500       46.13%    passed     90.19%
 159  MW828748|wild_canid|2019.500     46.13%    passed     89.86%
 160  MW828747|wild_canid|2016.500     46.13%    passed     75.87%
 161  MW828746|wild_canid|2016.500     46.13%    passed     75.87%
 162  MW828745|wild_canid|2016.500     46.13%    passed     74.34%
 163  MW828744|wild_canid|2018.500     46.13%    passed     70.73%
 164  MW828743|wild_canid|2018.500     46.13%    passed     69.18%
 165  MW828741|wild_canid|2016.500     46.13%    passed     70.99%
 166  MW828740|wild_canid|2017.500     46.13%    passed     70.99%
 167  MW828742|wild_canid|2018.500     46.13%    passed     69.18%
 168  MW828739|wild_canid|2016.500     46.13%    passed     68.43%
 169  MW828738|wild_canid|2017.500     46.13%    passed     71.36%
 170  MW828736|wild_canid|2017.500     46.13%    passed     74.34%
 171  MW828737|wild_canid|2018.500     46.13%    passed     75.87%
 172  MW828735|wild_canid|2020.500     46.18%    passed     80.69%
 173  MW828734|wild_canid|2016.500     46.13%    passed     82.03%
 174  MW828733|wild_canid|2016.500     46.13%    passed     82.64%
 175  MW828732|wild_canid|2016.500     46.13%    passed     82.64%
 176  MW828731|wild_canid|2016.500     46.13%    passed     82.64%
 177  KJ600776|procyonid|2012.962      11.12%    passed     92.48%
 178  KJ600775|procyonid|2013.195      11.12%    passed     94.05%
 179  KJ600774|procyonid|2013.181      11.12%    passed     95.61%
 180  KJ600773|procyonid|2013.175      11.12%    passed     94.58%
 181  OP209187|mustelid|2019.230        8.25%    passed     99.82%
 182  MW036824|wild_canid|2020.500     76.21%    passed     57.57%
 183  MW036806|wild_canid|2019.500     76.21%    passed     57.57%
 184  MW036805|mustelid|2019.500       76.21%    passed     57.57%
 185  MW036804|wild_canid|2019.500     76.21%    passed     57.57%
 186  MW036801|wild_canid|2020.500     76.21%    passed     57.57%
 187  MW036799|wild_canid|2019.500     76.21%    passed     57.57%
 188  MW036797|wild_canid|2019.500     76.21%    passed     57.57%
 189  MW036796|wild_canid|2019.500     76.21%    passed     57.57%
 190  MW036786|wild_canid|2019.500     76.21%    passed     57.57%
 191  MW036785|wild_canid|2019.500     76.21%    passed     57.57%
 192  MW036784|wild_canid|2019.500     76.21%    passed     57.57%
 193  MW036776|wild_canid|2019.500     76.21%    passed     57.57%
 194  MW036809|mustelid|2019.500       76.21%    passed     55.78%
 195  MW036823|wild_canid|2020.500     76.21%    passed     69.50%
 196  MW036822|wild_canid|2020.500     76.21%    passed     69.50%
 197  MW036821|wild_canid|2019.500     76.21%    passed     69.50%
 198  MW036819|wild_canid|2019.500     76.21%    passed     69.50%
 199  MW036818|wild_canid|2018.500     76.21%    passed     69.50%
 200  MW036816|wild_canid|2018.500     76.21%    passed     69.50%
 201  MW036815|wild_canid|2019.500     76.21%    passed     69.50%
 202  MW036814|wild_canid|2018.500     76.21%    passed     69.50%
 203  MW036813|wild_canid|2019.500     76.21%    passed     69.50%
 204  MW036812|wild_canid|2018.500     76.21%    passed     69.50%
 205  MW036811|wild_canid|2018.500     76.21%    passed     69.50%
 206  MW036810|wild_canid|2019.500     76.21%    passed     69.50%
 207  MW036807|mustelid|2019.500       76.21%    passed     69.50%
 208  MW036802|mustelid|2019.500       76.21%    passed     69.50%
 209  MW036795|wild_canid|2018.500     76.21%    passed     69.50%
 210  MW036794|wild_canid|2018.500     76.21%    passed     69.50%
 211  MW036793|wild_canid|2018.500     76.21%    passed     69.50%
 212  MW036792|wild_canid|2018.500     76.21%    passed     69.50%
 213  MW036791|wild_canid|2019.500     76.21%    passed     69.50%
 214  MW036790|wild_canid|2018.500     76.21%    passed     69.50%
 215  MW036789|wild_canid|2019.500     76.21%    passed     69.50%
 216  MW036788|wild_canid|2018.500     76.21%    passed     69.50%
 217  MW036783|mustelid|2019.500       76.21%    passed     69.50%
 218  MW036780|wild_canid|2020.500     76.21%    passed     69.50%
 219  MW036779|wild_canid|2019.500     76.21%    passed     69.50%
 220  MW036778|wild_canid|2018.500     76.21%    passed     69.50%
 221  MW036775|wild_canid|2019.500     76.21%    passed     69.50%
 222  MW036774|mustelid|2019.500       76.21%    passed     69.50%
 223  MW036803|wild_canid|2009.500     76.21%    passed     75.75%
 224  PX656924|domestic_dog|2024.637    8.25%    passed     99.15%
 225  MT119979|domestic_dog|2019.622    9.86%    passed     99.97%
 226  MH484613|domestic_dog|2017.500    8.25%    passed     98.40%
 227  OR238917|wild_canid|2023.500     63.13%    passed     91.65%
 228  PX656923|domestic_dog|2022.567    8.25%    passed     99.56%
 229  PX656922|domestic_dog|2011.553    8.25%    passed     99.70%
 230  ON533748|domestic_dog|2015.500    8.25%    passed     94.87%
 231  ON533747|domestic_dog|2015.500    8.25%    passed     95.89%
 232  JX912971|domestic_dog|2010.500    9.31%    passed     93.96%
 233  JX912966|domestic_dog|2008.500    9.31%    passed     99.01%
 234  JX912977|domestic_dog|2011.500   65.09%    passed     77.50%
 235  JX912973|domestic_dog|2012.500   65.09%    passed     77.50%
 236  JX912974|domestic_dog|2012.500   65.09%    passed     85.25%
 237  JX912969|domestic_dog|2008.500   65.09%    passed     88.93%
 238  JX912972|domestic_dog|2011.500   65.09%    passed     78.05%
 239  JX912970|domestic_dog|2009.500   65.09%    passed     79.46%
 240  JX912967|domestic_dog|2008.500   65.09%    passed     80.29%
 241  JX912957|domestic_dog|2009.500   65.09%    passed     85.73%
 242  JX912956|domestic_dog|2009.500   65.09%    passed     85.73%
 243  JX912962|domestic_dog|2012.500   65.09%    passed     91.88%
 244  FJ011004|domestic_dog|2003.874    8.40%    passed     95.34%
 245  FJ392652|domestic_dog|2003.500    8.25%    passed     95.89%
 246  JX912978|domestic_dog|2012.500    9.31%    passed     98.71%
 247  JX912976|domestic_dog|2012.500    9.31%    passed     96.00%
 248  AM422868|domestic_dog|2003.500   56.19%    passed     99.80%
 249  JX912965|domestic_dog|2008.500    9.31%    passed     99.36%
 250  MK423863|domestic_dog|2018.537    8.25%    passed     96.33%
 251  KT429766|domestic_dog|2012.604    8.25%    passed     95.24%

0

In [17]:
run_script("05_tree_summary.py",
           "--tree", "data/processed/H_ml.treefile",
           "--write-table")

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/05_tree_summary.py --tree data/processed/H_ml.treefile --write-table

================================================================
  1761 tips in H_ml.treefile
================================================================

HOST COMPOSITION
  domestic_dog         915   52.0%
  wild_canid           386   21.9%  <- wild
  mustelid             203   11.5%  <- wild
  procyonid            144    8.2%  <- wild
  wild_felid            63    3.6%  <- wild
  other                 16    0.9%
  ailurid                9    0.5%  <- wild
  pinniped               8    0.5%  <- wild
  primate                7    0.4%
  viverrid               6    0.3%  <- wild
  ursid                  4    0.2%  <- wild

  wild carnivores total: 823 (46.7%)
  sampling years: 1982.1 - 2026.5

================================================================
  MAJOR CLADES (8 groups)
  Structural split of the tree, not published lineage assignment.
================================================================

  clade_1  (1241 tips)
    years: 1992.0 - 2025.7  (span 33.7)
    domestic_dog        596
    wild_canid          280  <-
    mustelid            147  <-
    procyonid           129  <-
    wild_felid           54  <-
    other                14
    primate               7
    ailurid               6  <-
    viverrid              5  <-
    ursid                 3  <-
    >> 624 wild carnivore tips in this clade

  clade_2  (165 tips)
    years: 1988.5 - 2026.5  (span 38.0)
    domestic_dog        106
    wild_canid           34  <-
    mustelid             18  <-
    wild_felid            5  <-
    pinniped              2  <-
    >> 59 wild carnivore tips in this clade

  clade_3  (109 tips)
    years: 2003.5 - 2023.7  (span 20.2)
    wild_canid           56  <-
    domestic_dog         41
    mustelid              5  <-
    procyonid             5  <-
    ursid                 1  <-
    viverrid              1  <-
    >> 68 wild carnivore tips in this clade

  clade_4  (86 tips)
    years: 2009.3 - 2024.1  (span 14.8)
    domestic_dog         64
    procyonid             9  <-
    wild_canid            7  <-
    mustelid              4  <-
    ailurid               2  <-
    >> 22 wild carnivore tips in this clade

  clade_5  (72 tips)
    years: 1982.1 - 2023.4  (span 41.3)
    domestic_dog         33
    mustelid             29  <-
    pinniped              6  <-
    wild_felid            2  <-
    procyonid             1  <-
    ailurid               1  <-
    >> 39 wild carnivore tips in this clade

  clade_6  (45 tips)
    years: 2011.8 - 2021.9  (span 10.1)
    domestic_dog         43
    wild_canid            2  <-
    >> 2 wild carnivore tips in this clade

  clade_7  (41 tips)
    years: 2003.5 - 2017.0  (span 13.5)
    domestic_dog         30
    wild_canid            7  <-
    other                 2
    wild_felid            2  <-
    >> 9 wild carnivore tips in this clade

  clade_8_small  (2 tips)
    years: 2017.8 - 2022.6  (span 4.7)
    domestic_dog          2

================================================================
  WILD CARNIVORE TIPS BY CLADE
================================================================
  clade_1           624 wild   (wild_canid 280, mustelid 147, procyonid 129, wild_felid 54, ailurid 6, viverrid 5, ursid 3)
  clade_3            68 wild   (wild_canid 56, mustelid 5, procyonid 5, ursid 1, viverrid 1)
  clade_2            59 wild   (wild_canid 34, mustelid 18, wild_felid 5, pinniped 2)
  clade_5            39 wild   (mustelid 29, pinniped 6, wild_felid 2, procyonid 1, ailurid 1)
  clade_4            22 wild   (procyonid 9, wild_canid 7, mustelid 4, ailurid 2)
  clade_7             9 wild   (wild_canid 7, wild_felid 2)
  clade_6             2 wild   (wild_canid 2)

  The clade with the most wild carnivore tips and a decent time span
  is the natural candidate for a focused within-lineage analysis.

per-tip clade table -> data/processed/H_ml_clades.tsv
Use it to pull a subset alignment for the focused analysis.

0

In [18]:
run_script("05_tree_summary.py", "--tree", "data/processed/H_ml.treefile",
           "--n-clades", "20", "--write-table")

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/05_tree_summary.py --tree data/processed/H_ml.treefile --n-clades 20 --write-table

================================================================
  1761 tips in H_ml.treefile
================================================================

HOST COMPOSITION
  domestic_dog         915   52.0%
  wild_canid           386   21.9%  <- wild
  mustelid             203   11.5%  <- wild
  procyonid            144    8.2%  <- wild
  wild_felid            63    3.6%  <- wild
  other                 16    0.9%
  ailurid                9    0.5%  <- wild
  pinniped               8    0.5%  <- wild
  primate                7    0.4%
  viverrid               6    0.3%  <- wild
  ursid                  4    0.2%  <- wild

  wild carnivores total: 823 (46.7%)
  sampling years: 1982.1 - 2026.5

================================================================
  MAJOR CLADES (20 groups)
  Structural split of the tree, not published lineage assignment.
================================================================

  clade_1  (430 tips)
    years: 2004.5 - 2025.7  (span 21.2)
    domestic_dog        334
    wild_canid           50  <-
    mustelid             36  <-
    viverrid              4  <-
    ursid                 3  <-
    wild_felid            2  <-
    procyonid             1  <-
    >> 96 wild carnivore tips in this clade

  clade_2  (409 tips)
    years: 1998.1 - 2025.5  (span 27.4)
    wild_canid          175  <-
    domestic_dog        147
    mustelid             77  <-
    procyonid             6  <-
    wild_felid            4  <-
    >> 262 wild carnivore tips in this clade

  clade_3  (204 tips)
    years: 1992.0 - 2023.6  (span 31.6)
    procyonid           112  <-
    wild_canid           38  <-
    mustelid             33  <-
    wild_felid           11  <-
    domestic_dog          9
    ailurid               1  <-
    >> 195 wild carnivore tips in this clade

  clade_4  (165 tips)
    years: 1988.5 - 2026.5  (span 38.0)
    domestic_dog        106
    wild_canid           34  <-
    mustelid             18  <-
    wild_felid            5  <-
    pinniped              2  <-
    >> 59 wild carnivore tips in this clade

  clade_5  (111 tips)
    years: 1994.0 - 2025.7  (span 31.7)
    domestic_dog         50
    wild_felid           34  <-
    other                14
    wild_canid           10  <-
    ailurid               2  <-
    viverrid              1  <-
    >> 47 wild carnivore tips in this clade

  clade_6  (109 tips)
    years: 2003.5 - 2023.7  (span 20.2)
    wild_canid           56  <-
    domestic_dog         41
    mustelid              5  <-
    procyonid             5  <-
    ursid                 1  <-
    viverrid              1  <-
    >> 68 wild carnivore tips in this clade

  clade_7  (86 tips)
    years: 2009.3 - 2024.1  (span 14.8)
    domestic_dog         64
    procyonid             9  <-
    wild_canid            7  <-
    mustelid              4  <-
    ailurid               2  <-
    >> 22 wild carnivore tips in this clade

  clade_8  (72 tips)
    years: 1982.1 - 2023.4  (span 41.3)
    domestic_dog         33
    mustelid             29  <-
    pinniped              6  <-
    wild_felid            2  <-
    procyonid             1  <-
    ailurid               1  <-
    >> 39 wild carnivore tips in this clade

  clade_9  (45 tips)
    years: 2011.8 - 2021.9  (span 10.1)
    domestic_dog         43
    wild_canid            2  <-
    >> 2 wild carnivore tips in this clade

  clade_10  (41 tips)
    years: 2003.5 - 2017.0  (span 13.5)
    domestic_dog         30
    wild_canid            7  <-
    other                 2
    wild_felid            2  <-
    >> 9 wild carnivore tips in this clade

  clade_11  (28 tips)
    years: 2014.5 - 2020.1  (span 5.6)
    domestic_dog         28

  clade_12  (23 tips)
    years: 2005.2 - 2020.3  (span 15.1)
    domestic_dog         23

  clade_13  (11 tips)
    years: 2006.5 - 2020.3  (span 13.8)
    primate               7
    domestic_dog          4

  clade_14  (10 tips)
    years: 2010.5 - 2014.5  (span 4.0)
    procyonid             9  <-
    mustelid              1  <-
    >> 10 wild carnivore tips in this clade

  clade_15  (6 tips)
    years: 2007.3 - 2016.2  (span 8.9)
    wild_canid            5  <-
    procyonid             1  <-
    >> 6 wild carnivore tips in this clade

  clade_16  (5 tips)
    years: 2013.8 - 2015.9  (span 2.1)
    ailurid               3  <-
    wild_felid            2  <-
    >> 5 wild carnivore tips in this clade

  clade_17_small  (2 tips)
    years: 2017.8 - 2022.6  (span 4.7)
    domestic_dog          2

  clade_18_small  (2 tips)
    years: 2010.0 - 2010.2  (span 0.2)
    wild_felid            1  <-
    wild_canid            1  <-
    >> 2 wild carnivore tips in this clade

  clade_19_small  (1 tips)
    years: 2007.5 - 2007.5  (span 0.0)
    wild_canid            1  <-
    >> 1 wild carnivore tips in this clade

  clade_20_small  (1 tips)
    years: 2020.3 - 2020.3  (span 0.0)
    domestic_dog          1

================================================================
  WILD CARNIVORE TIPS BY CLADE
================================================================
  clade_2           262 wild   (wild_canid 175, mustelid 77, procyonid 6, wild_felid 4)
  clade_3           195 wild   (procyonid 112, wild_canid 38, mustelid 33, wild_felid 11, ailurid 1)
  clade_1            96 wild   (wild_canid 50, mustelid 36, viverrid 4, ursid 3, wild_felid 2, procyonid 1)
  clade_6            68 wild   (wild_canid 56, mustelid 5, procyonid 5, ursid 1, viverrid 1)
  clade_4            59 wild   (wild_canid 34, mustelid 18, wild_felid 5, pinniped 2)
  clade_5            47 wild   (wild_felid 34, wild_canid 10, ailurid 2, viverrid 1)
  clade_8            39 wild   (mustelid 29, pinniped 6, wild_felid 2, procyonid 1, ailurid 1)
  clade_7            22 wild   (procyonid 9, wild_canid 7, mustelid 4, ailurid 2)
  clade_14           10 wild   (procyonid 9, mustelid 1)
  clade_10            9 wild   (wild_canid 7, wild_felid 2)
  clade_15            6 wild   (wild_canid 5, procyonid 1)
  clade_16            5 wild   (ailurid 3, wild_felid 2)
  clade_9             2 wild   (wild_canid 2)
  clade_18_small      2 wild   (wild_felid 1, wild_canid 1)
  clade_19_small      1 wild   (wild_canid 1)

  The clade with the most wild carnivore tips and a decent time span
  is the natural candidate for a focused within-lineage analysis.

per-tip clade table -> data/processed/H_ml_clades.tsv
Use it to pull a subset alignment for the focused analysis.

0

In [19]:
# global, stratified to 400
run_script("06_subsample.py", "--mode", "global", "--target", "400",
           "--aln", "data/processed/H_aligned.fasta",
           "--clades", "data/processed/H_ml_clades.tsv",
           "--metadata", "data/processed/metadata_clean.tsv")

# clade_3, the wildlife-maintained lineage — keeps all 204
run_script("06_subsample.py", "--mode", "clade", "--clade", "clade_3",
           "--aln", "data/processed/H_aligned.fasta",
           "--clades", "data/processed/H_ml_clades.tsv",
           "--metadata", "data/processed/metadata_clean.tsv")

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/06_subsample.py --mode global --target 400 --aln data/processed/H_aligned.fasta --clades data/processed/H_ml_clades.tsv --metadata data/processed/metadata_clean.tsv

Loaded 1761 aligned sequences

Pool (global): 1761 sequences
    domestic_dog       915
    wild_canid         386  <- wild
    mustelid           203  <- wild
    procyonid          144  <- wild
    wild_felid          63  <- wild
    other               16
    ailurid              9  <- wild
    pinniped             8  <- wild
    primate              7
    viverrid             6  <- wild
    ursid                4  <- wild
    wild total         823  (46.7%)
    years 1982.1 - 2026.5
    clades: clade_1=430, clade_2=409, clade_3=204, clade_4=165, clade_5=111, clade_6=109, clade_7=86, clade_8=72

Removed 332 exact duplicate sequences (kept the best-dated representative of each)

stratified subsample to 400

FINAL SUBSET: 400 sequences
    domestic_dog       205
    wild_canid          70  <- wild
    mustelid            48  <- wild
    wild_felid          27  <- wild
    procyonid           25  <- wild
    ailurid              7  <- wild
    other                6
    pinniped             5  <- wild
    viverrid             3  <- wild
    primate              2
    ursid                2  <- wild
    wild total         187  (46.8%)
    years 1982.1 - 2026.5
    clades: clade_1=109, clade_2=58, clade_4=38, clade_3=36, clade_5=34, clade_6=28, clade_8=25, clade_7=20

  WARNING: wild host groups with <5 sequences: {'ursid': 2, 'viverrid': 3}
  Discrete trait analysis will be unreliable for these. Consider merging
  them into a broader category, or raising --target.

wrote data/processed/H_global400.fasta
wrote data/processed/H_global400_metadata.tsv
wrote data/processed/H_global400_dates.tsv

Next: rebuild an ML tree on the subset and re-check TempEst before BEAST —
a subset with better temporal balance often has much stronger clock signal.
    python scripts/03_align_and_tree.py --fasta data/processed/H_global400.fasta \
        --metadata data/processed/H_global400_metadata.tsv --prefix H_global400

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/06_subsample.py --mode clade --clade clade_3 --aln data/processed/H_aligned.fasta --clades data/processed/H_ml_clades.tsv --metadata data/processed/metadata_clean.tsv

Loaded 1761 aligned sequences

Pool (clade_3): 204 sequences
    procyonid          112  <- wild
    wild_canid          38  <- wild
    mustelid            33  <- wild
    wild_felid          11  <- wild
    domestic_dog         9
    ailurid              1  <- wild
    wild total         195  (95.6%)
    years 1992.0 - 2023.6

Removed 42 exact duplicate sequences (kept the best-dated representative of each)

all sequences retained

FINAL SUBSET: 162 sequences
    procyonid           91  <- wild
    wild_canid          32  <- wild
    mustelid            23  <- wild
    domestic_dog         8
    wild_felid           7  <- wild
    ailurid              1  <- wild
    wild total         154  (95.1%)
    years 1992.0 - 2023.6

  WARNING: wild host groups with <5 sequences: {'ailurid': 1}
  Discrete trait analysis will be unreliable for these. Consider merging
  them into a broader category, or raising --target.

wrote data/processed/H_clade_3.fasta
wrote data/processed/H_clade_3_metadata.tsv
wrote data/processed/H_clade_3_dates.tsv

Next: rebuild an ML tree on the subset and re-check TempEst before BEAST —
a subset with better temporal balance often has much stronger clock signal.
    python scripts/03_align_and_tree.py --fasta data/processed/H_clade_3.fasta \
        --metadata data/processed/H_clade_3_metadata.tsv --prefix H_clade_3

0

---
## Session log

Keep notes here as you go. Decisions you make now will need justifying in the methods
section in four months, and you will not remember why.

In [20]:
import subprocess, shutil
from pathlib import Path

SUBSETS = ["H_global400", "H_clade_3"]   # add "H_clade_2", "H_clade_5" etc. as you make them
PROC = Path("data/processed")

def read_fasta(p):
    seqs, name, chunks = {}, None, []
    for line in Path(p).read_text().splitlines():
        if line.startswith(">"):
            if name: seqs[name] = "".join(chunks)
            name, chunks = line[1:].split()[0], []
        elif line.strip():
            chunks.append(line.strip())
    if name: seqs[name] = "".join(chunks)
    return seqs

def write_fasta(p, seqs, width=60):
    with Path(p).open("w") as fh:
        for n, s in seqs.items():
            fh.write(f">{n}\n")
            for i in range(0, len(s), width):
                fh.write(s[i:i+width] + "\n")

iqtree = shutil.which("iqtree2") or shutil.which("iqtree")
if not iqtree:
    raise RuntimeError("iqtree not found — conda activate cdv-phylo")

for name in SUBSETS:
    fasta = PROC / f"{name}.fasta"
    if not fasta.is_file():
        print(f"skipping {name} — {fasta} not found\n"); continue

    seqs = read_fasta(fasta)
    L = len(next(iter(seqs.values())))
    keep = [i for i in range(L) if any(s[i] not in "-." for s in seqs.values())]
    clean = PROC / f"{name}_clean.fasta"
    write_fasta(clean, {k: "".join(v[i] for i in keep) for k, v in seqs.items()})
    print(f"{name}: {len(seqs)} seqs, {L} -> {len(keep)} columns "
          f"({L - len(keep)} all-gap removed)")

    cmd = [iqtree, "-s", str(clean), "-m", "MFP", "-B", "1000",
           "--alrt", "1000", "-T", "AUTO",
           "--prefix", str(PROC / f"{name}_ml"), "-redo"]
    print("$", " ".join(cmd))
    proc = subprocess.run(cmd, capture_output=True, text=True)
    print(proc.stdout[-1500:] if proc.returncode == 0 else proc.stdout[-3000:] + proc.stderr[-2000:])
    print(f"--> {PROC / f'{name}_ml.treefile'}\n" + "="*60 + "\n")

H_global400: 400 seqs, 1988 -> 1987 columns (1 all-gap removed)
$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/iqtree2 -s data/processed/H_global400_clean.fasta -m MFP -B 1000 --alrt 1000 -T AUTO --prefix data/processed/H_global400_ml -redo
99  C: 0.211  G: 0.214  T: 0.276
Site proportion and rates:  (0.476,0.209) (0.452,1.412) (0.072,3.647)
Parameters optimization took 1 rounds (0.484 sec)
BEST SCORE FOUND : -32274.152

Testing tree branches by SH-like aLRT with 1000 replicates...
3.387 sec.
Creating bootstrap support values...
Split supports printed to NEXUS file data/processed/H_global400_ml.splits.nex
Total tree length: 5.088

Total number of iterations: 389
CPU time used for tree search: 4166.987 sec (1h:9m:26s)
Wall-clock time used for tree search: 1679.575 sec (0h:27m:59s)
Total CPU time used: 4190.247 sec (1h:9m:50s)
Total wall-clock time used: 1686.567 sec (0h:28m:6s)

Computing bootstrap consensus tree...
Reading input file data/processed/H_global400_ml.splits.nex...
400 taxa and 2344 splits.
Consensus tree written to data/processed/H_global400_ml.contree
Reading input trees file data/processed/H_global400_ml.contree
Log-likelihood of consensus tree: -32275.183

Analysis results written to:
  IQ-TREE report:                data/processed/H_global400_ml.iqtree
  Maximum-likelihood tree:       data/processed/H_global400_ml.treefile
  Likelihood distances:          data/processed/H_global400_ml.mldist

Ultrafast bootstrap approximation results written to:
  Split support values:          data/processed/H_global400_ml.splits.nex
  Consensus tree:                data/processed/H_global400_ml.contree
  Screen log file:               data/processed/H_global400_ml.log

Date and Time: Thu Aug 27 13:39:16 2026

--> data/processed/H_global400_ml.treefile
============================================================

H_clade_3: 162 seqs, 1988 -> 1950 columns (38 all-gap removed)
$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/iqtree2 -s data/processed/H_clade_3_clean.fasta -m MFP -B 1000 --alrt 1000 -T AUTO --prefix data/processed/H_clade_3_ml -redo
.60312  C-G: 0.60312  C-T: 5.04580  G-T: 1.00000
Base frequencies:  A: 0.303  C: 0.211  G: 0.214  T: 0.273
Gamma shape alpha: 0.576
Parameters optimization took 1 rounds (0.035 sec)
BEST SCORE FOUND : -8336.414

Testing tree branches by SH-like aLRT with 1000 replicates...
1.376 sec.
Creating bootstrap support values...
Split supports printed to NEXUS file data/processed/H_clade_3_ml.splits.nex
Total tree length: 0.555

Total number of iterations: 171
CPU time used for tree search: 268.930 sec (0h:4m:28s)
Wall-clock time used for tree search: 92.107 sec (0h:1m:32s)
Total CPU time used: 274.967 sec (0h:4m:34s)
Total wall-clock time used: 94.407 sec (0h:1m:34s)

Computing bootstrap consensus tree...
Reading input file data/processed/H_clade_3_ml.splits.nex...
162 taxa and 2070 splits.
Consensus tree written to data/processed/H_clade_3_ml.contree
Reading input trees file data/processed/H_clade_3_ml.contree
Log-likelihood of consensus tree: -8336.727

Analysis results written to:
  IQ-TREE report:                data/processed/H_clade_3_ml.iqtree
  Maximum-likelihood tree:       data/processed/H_clade_3_ml.treefile
  Likelihood distances:          data/processed/H_clade_3_ml.mldist

Ultrafast bootstrap approximation results written to:
  Split support values:          data/processed/H_clade_3_ml.splits.nex
  Consensus tree:                data/processed/H_clade_3_ml.contree
  Screen log file:               data/processed/H_clade_3_ml.log

Date and Time: Thu Aug 27 13:41:32 2026

--> data/processed/H_clade_3_ml.treefile
============================================================

In [21]:
import pandas as pd
from pathlib import Path

PROC = Path("data/processed")
sub = pd.read_csv(PROC / "H_clade_3_metadata.tsv", sep="\t")

# join back to the full metadata for country, strain, description
clean = pd.read_csv(PROC / "metadata_clean.tsv", sep="\t")
clean["acc_base"] = clean["accession"].astype(str).str.split(".").str[0]
cols = [c for c in ["acc_base","description","country","host_raw","host_canonical",
                    "strain","isolate","collection_date"] if c in clean.columns]
d = sub.merge(clean[cols], left_on="accession", right_on="acc_base", how="left")

WILD = {"wild_felid","wild_canid","mustelid","procyonid","pinniped",
        "ursid","ailurid","viverrid"}

print(f"clade_3: {len(d)} sequences\n")
print("HOST COMPOSITION")
h = d["host_group"].value_counts()
for host, n in h.items():
    print(f"  {host:<16} {n:>4}  {n/len(d):>6.1%}{'  <- wild' if host in WILD else ''}")
n_wild = sum(n for k, n in h.items() if k in WILD)
print(f"  {'WILD TOTAL':<16} {n_wild:>4}  {n_wild/len(d):>6.1%}")

print("\nCANONICAL HOST SPECIES (top 15)")
print(d["host_canonical"].value_counts().head(15).to_string())

print("\nGEOGRAPHY")
print(d["country"].value_counts().head(15).to_string())
print(f"  countries: {d['country'].nunique()}  |  missing: {d['country'].isna().sum()}")

print("\nHOST x DECADE")
d["decade"] = (d["decimal_year"] // 10 * 10).astype("Int64")
print(pd.crosstab(d["host_group"], d["decade"]).to_string())

print("\nDATE PRECISION")
print(d["date_precision"].value_counts().to_string())
print(f"  span: {d['decimal_year'].min():.1f} - {d['decimal_year'].max():.1f}")

print("\n" + "="*66)
print("THE 9 DOMESTIC DOGS — the most interesting tips in this clade")
print("="*66)
dogs = d[d["host_group"] == "domestic_dog"]
print(dogs[["accession","country","collection_date","strain","description"]]
      .to_string(index=False, max_colwidth=55))

unresolved = d[d["host_group"].isin(["other","unknown","unparsed"])]
if len(unresolved):
    print(f"\nUNRESOLVED HOSTS ({len(unresolved)}) — check these")
    print(unresolved[["accession","host_raw","description"]].to_string(index=False, max_colwidth=55))

clade_3: 162 sequences

HOST COMPOSITION
  procyonid          91   56.2%  <- wild
  wild_canid         32   19.8%  <- wild
  mustelid           23   14.2%  <- wild
  domestic_dog        8    4.9%
  wild_felid          7    4.3%  <- wild
  ailurid             1    0.6%  <- wild
  WILD TOTAL        154   95.1%

CANONICAL HOST SPECIES (top 15)
host_canonical
Procyon lotor               91
Canis latrans               16
Mephitis mephitis           14
Vulpes vulpes               10
Canis lupus familiaris       8
Panthera tigris              5
Neovison vison               5
Urocyon cinereoargenteus     3
Martes sp.                   3
Vulpes sp.                   2
Panthera leo                 1
Panthera pardus              1
Canis lupus                  1
Meles meles                  1
Ailurus fulgens              1

GEOGRAPHY
country
Canada     114
USA         44
Denmark      4
  countries: 3  |  missing: 0

HOST x DECADE
decade        1990  2000  2010  2020
host_group
ailurid          0     0     1     0
domestic_dog     0     2     4     2
mustelid         0     4    19     0
procyonid        1     0    85     5
wild_canid       0     0    32     0
wild_felid       2     0     5     0

DATE PRECISION
date_precision
year     126
day       34
month      2
  span: 1992.0 - 2023.6

==================================================================
THE 9 DOMESTIC DOGS — the most interesting tips in this clade
==================================================================
accession country collection_date strain                                             description
 EU716337     USA      2004-09-04    NaN  Canine distemper virus isolate 164071, complete genome
 MH810099     USA      2017-12-21    134 Morbillivirus canis strain 134 hemagglutinin (H) mRN...
 PX789678     USA         2021-01    NaN Canine distemper virus isolate MI_Dog1_2021 hemagglu...
 PX789674     USA         2023-08    NaN Canine distemper virus isolate MI_Dog4_2023 hemagglu...
 KJ123771     USA            2004    NaN Canine distemper virus isolate 171391-513, complete ...
 MG797669     USA            2017    NaN Morbillivirus canis isolate MN hemagglutinin (H) gen...
 JF283477     USA            2010    NaN Canine distemper virus isolate 10453WY hemagglutinin...
 OK666917  Canada            2012    NaN Morbillivirus canis isolate 12-057269-0001 hemagglut...

In [22]:
run_script("07_make_beast_xml.py", "--aln", "data/processed/H_clade_3_clean.fasta",
           "--out", "beast/drt", "--rate", "7.46e-4",
           "--chain", "20000000", "--randomize-dates", "20")

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/07_make_beast_xml.py --aln data/processed/H_clade_3_clean.fasta --out beast/drt --rate 7.46e-4 --chain 20000000 --randomize-dates 20

162 sequences, 1950 sites
date range: 1992.00 - 2023.62 (31.6 yrs)
host groups: {'procyonid': 91, 'wild_canid': 32, 'mustelid': 23, 'domestic_dog': 8, 'wild_felid': 7, 'ailurid': 1}
rate prior mean: 0.000746   chain: 20,000,000   log every: 2,000

WARNING: host groups with <5 sequences: {'ailurid': 1}
  Discrete trait analysis will be unreliable for these — consider merging.

wrote beast/drt/H_clade_3_clean_traits.txt   <- import this in BEAUti for the discrete trait
wrote beast/drt/H_clade_3_clean.xml   (well-formed XML)
wrote 20 date-randomised replicates -> beast/drt/date_randomised
  Run these, then compare the ucldMean 95% HPDs against the real analysis.
  Real estimate outside the randomised distribution = genuine temporal signal.

NEXT STEPS

1. Open H_clade_3_clean.xml in BEAUti (File > Load) and confirm it parses cleanly.
   This is your check that the XML matches your BEAST version. Do it before
   committing days of compute.

2. Add the discrete trait analysis in BEAUti:
     - Install BEAST_CLASSIC via File > Manage Packages (restart BEAUti after)
     - Tip Dates tab: confirm dates loaded, 'since some time in the past' unticked
     - Add a trait partition and import H_clade_3_clean_traits.txt
     - Set the trait substitution model to asymmetric, tick BSSVS
     - BSSVS matters: it identifies which host transitions are actually supported
       rather than fitting every possible one
     - Save the XML

3. Test run: chainLength 1000000, confirm it starts and the likelihood climbs.

4. Full run, at least 2 independent chains with different seeds:
     beast -seed 12345 -threads 4 H_clade_3_clean.xml
     beast -seed 54321 -threads 4 H_clade_3_clean.xml

5. Tracer: every parameter ESS > 200, chains converged on the same values.

6. Date randomisation test, then TreeAnnotator for the MCC tree.

0

In [23]:
from pathlib import Path
for d in ["data/processed", "beast", "beast/clade3"]:
    p = Path(d)
    print(f"\n{d}:", "(missing)" if not p.is_dir() else "")
    if p.is_dir():
        for f in sorted(p.iterdir()):
            print(f"   {f.name:<45} {f.stat().st_size/1024:>8.1f} KB")

data/processed:
   .gitkeep                                           0.0 KB
   H_aligned.fasta                                 3530.0 KB
   H_clade_3.fasta                                  324.5 KB
   H_clade_3_clean.fasta                            318.3 KB
   H_clade_3_dates.tsv                                5.9 KB
   H_clade_3_metadata.tsv                            12.9 KB
   H_clade_3_ml.bionj                                 9.1 KB
   H_clade_3_ml.ckp.gz                              280.6 KB
   H_clade_3_ml.contree                               9.2 KB
   H_clade_3_ml.iqtree                               90.4 KB
   H_clade_3_ml.log                                  34.6 KB
   H_clade_3_ml.mldist                              261.4 KB
   H_clade_3_ml.model.gz                              7.2 KB
   H_clade_3_ml.splits.nex                          123.9 KB
   H_clade_3_ml.treefile                              9.7 KB
   H_dates.tsv                                       66.4 KB
   H_global400.fasta                                801.8 KB
   H_global400_clean.fasta                          801.4 KB
   H_global400_dates.tsv                             15.1 KB
   H_global400_metadata.tsv                          44.6 KB
   H_global400_ml.bionj                              22.6 KB
   H_global400_ml.ckp.gz                            624.0 KB
   H_global400_ml.contree                            23.4 KB
   H_global400_ml.iqtree                            166.3 KB
   H_global400_ml.log                                61.4 KB
   H_global400_ml.mldist                           1575.0 KB
   H_global400_ml.model.gz                           19.6 KB
   H_global400_ml.splits.nex                        206.3 KB
   H_global400_ml.treefile                           25.0 KB
   H_labelled.fasta                                2558.5 KB
   H_ml.bionj                                        90.5 KB
   H_ml.ckp.gz                                     4569.7 KB
   H_ml.contree                                     102.7 KB
   H_ml.iqtree                                      854.2 KB
   H_ml.log                                         182.4 KB
   H_ml.mldist                                    25206.7 KB
   H_ml.model.gz                                     92.2 KB
   H_ml.splits.nex                                 2093.9 KB
   H_ml.treefile                                    108.3 KB
   H_ml.uniqueseq.phy                              3166.1 KB
   H_ml_clades.tsv                                   62.8 KB
   metadata_clean.tsv                               433.2 KB
   sequences_H.fasta                               2526.5 KB
   sequences_all.fasta                             5527.1 KB

beast:
   drt                                                0.2 KB

beast/clade3: (missing)

In [ ]:
# 2026-__-__
# records fetched:
# retained after curation:
# host patterns added:
# records dropped by hand, and why:
# gate decision:

In [24]:
run_script("07_make_beast_xml.py",
           "--aln", "data/processed/H_clade_3.fasta",
           "--out", "beast/clade3",
           "--rate", "7.46e-4",
           "--chain", "100000000")

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/07_make_beast_xml.py --aln data/processed/H_clade_3.fasta --out beast/clade3 --rate 7.46e-4 --chain 100000000

162 sequences, 1988 sites
date range: 1992.00 - 2023.62 (31.6 yrs)
host groups: {'procyonid': 91, 'wild_canid': 32, 'mustelid': 23, 'domestic_dog': 8, 'wild_felid': 7, 'ailurid': 1}
rate prior mean: 0.000746   chain: 100,000,000   log every: 10,000

WARNING: host groups with <5 sequences: {'ailurid': 1}
  Discrete trait analysis will be unreliable for these — consider merging.

wrote beast/clade3/H_clade_3_traits.txt   <- import this in BEAUti for the discrete trait
wrote beast/clade3/H_clade_3.xml   (well-formed XML)

NEXT STEPS

1. Open H_clade_3.xml in BEAUti (File > Load) and confirm it parses cleanly.
   This is your check that the XML matches your BEAST version. Do it before
   committing days of compute.

2. Add the discrete trait analysis in BEAUti:
     - Install BEAST_CLASSIC via File > Manage Packages (restart BEAUti after)
     - Tip Dates tab: confirm dates loaded, 'since some time in the past' unticked
     - Add a trait partition and import H_clade_3_traits.txt
     - Set the trait substitution model to asymmetric, tick BSSVS
     - BSSVS matters: it identifies which host transitions are actually supported
       rather than fitting every possible one
     - Save the XML

3. Test run: chainLength 1000000, confirm it starts and the likelihood climbs.

4. Full run, at least 2 independent chains with different seeds:
     beast -seed 12345 -threads 4 H_clade_3.xml
     beast -seed 54321 -threads 4 H_clade_3.xml

5. Tracer: every parameter ESS > 200, chains converged on the same values.

6. Date randomisation test, then TreeAnnotator for the MCC tree.

0

In [25]:
run_script("07_make_beast_xml.py",
           "--aln", "data/processed/H_clade_3.fasta",
           "--out", "beast/clade3",
           "--rate", "7.46e-4",
           "--chain", "100000000")

$ /Users/batyanightingale/anaconda3/envs/cdv-phylo/bin/python scripts/07_make_beast_xml.py --aln data/processed/H_clade_3.fasta --out beast/clade3 --rate 7.46e-4 --chain 100000000

162 sequences, 1988 sites
date range: 1992.00 - 2023.62 (31.6 yrs)
host groups: {'procyonid': 91, 'wild_canid': 32, 'mustelid': 23, 'domestic_dog': 8, 'wild_felid': 7, 'ailurid': 1}
rate prior mean: 0.000746   chain: 100,000,000   log every: 10,000

WARNING: host groups with <5 sequences: {'ailurid': 1}
  Discrete trait analysis will be unreliable for these — consider merging.

wrote beast/clade3/H_clade_3_traits.txt   <- import this in BEAUti for the discrete trait
wrote beast/clade3/H_clade_3.xml   (well-formed XML)

NEXT STEPS

1. Open H_clade_3.xml in BEAUti (File > Load) and confirm it parses cleanly.
   This is your check that the XML matches your BEAST version. Do it before
   committing days of compute.

2. Add the discrete trait analysis in BEAUti:
     - Install BEAST_CLASSIC via File > Manage Packages (restart BEAUti after)
     - Tip Dates tab: confirm dates loaded, 'since some time in the past' unticked
     - Add a trait partition and import H_clade_3_traits.txt
     - Set the trait substitution model to asymmetric, tick BSSVS
     - BSSVS matters: it identifies which host transitions are actually supported
       rather than fitting every possible one
     - Save the XML

3. Test run: chainLength 1000000, confirm it starts and the likelihood climbs.

4. Full run, at least 2 independent chains with different seeds:
     beast -seed 12345 -threads 4 H_clade_3.xml
     beast -seed 54321 -threads 4 H_clade_3.xml

5. Tracer: every parameter ESS > 200, chains converged on the same values.

6. Date randomisation test, then TreeAnnotator for the MCC tree.

0

In [26]:
import xml.etree.ElementTree as ET
from pathlib import Path

XML = Path("beast/clade3/H_clade_3.xml")   # adjust to your filename
root = ET.parse(XML).getroot()
taxa = [s.get("taxon") for s in root.findall(".//sequence")]

print(f"{len(taxa)} taxa in the XML")
print("example:", repr(taxa[0]))

out = XML.parent
with (out / "traits_with_header.txt").open("w") as fh:
    fh.write("traits\thost\n")
    for t in taxa:
        fh.write(f"{t}\t{t.split('|')[1]}\n")

with (out / "traits_no_header.txt").open("w") as fh:
    for t in taxa:
        fh.write(f"{t}\t{t.split('|')[1]}\n")

print("wrote both variants to", out)
print("first data line:", repr(f"{taxa[0]}\t{taxa[0].split('|')[1]}"))

162 taxa in the XML
example: 'KU666057|procyonid|2012.896'
wrote both variants to beast/clade3
first data line: 'KU666057|procyonid|2012.896\tprocyonid'

In [27]:
import shutil, subprocess, time, re
from pathlib import Path

XML = Path("beast/clade3/H_clade_3.xml")   # <-- your edited test XML
SEED = 12345
THREADS = 4
TIMEOUT_MIN = 30        # kill it if the "test" turns into an all-nighter

def find_beast():
    exe = shutil.which("beast")
    if exe: return exe
    for pat in ["/Applications/BEAST*/bin/beast",
                str(Path.home() / "BEAST*/bin/beast"),
                str(Path.home() / "Applications/BEAST*/bin/beast")]:
        hits = sorted(Path(pat).parent.parent.parent.glob(Path(pat).relative_to(Path(pat).parents[2]).as_posix())) \
               if False else sorted(Path("/").glob(pat.lstrip("/")))
        if hits: return str(hits[-1])
    return None

beast = find_beast()
if not beast:
    raise RuntimeError("BEAST not found. Install from beast2.org, or set `beast` manually "
                       "to the full path of the executable inside BEAST*/bin/")
if not XML.is_file():
    raise FileNotFoundError(f"{XML} not found. Files in {XML.parent}: "
                            f"{sorted(p.name for p in XML.parent.iterdir()) if XML.parent.is_dir() else 'dir missing'}")

# confirm the chain length you actually set
chain = re.search(r'chainLength="(\d+)"', XML.read_text())
print(f"beast : {beast}")
print(f"xml   : {XML}")
print(f"chain : {int(chain.group(1)):,}" if chain else "chain : not found")
print("-" * 60)

cmd = [beast, "-seed", str(SEED), "-threads", str(THREADS),
       "-overwrite", "-working", str(XML)]
t0 = time.time()
proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                        text=True, bufsize=1)
posteriors, tail = [], []
try:
    for line in proc.stdout:
        line = line.rstrip()
        tail.append(line); tail[:] = tail[-40:]
        parts = line.split()
        if len(parts) >= 2 and parts[0].isdigit():
            try:
                posteriors.append(float(parts[1]))
            except ValueError:
                pass
            if len(posteriors) % 10 == 1:
                print(f"  [{time.time()-t0:6.0f}s] {line[:90]}")
        elif any(k in line for k in ("Error", "Exception", "error", "Fatal")):
            print("  !!", line)
        if time.time() - t0 > TIMEOUT_MIN * 60:
            proc.kill(); print(f"\nKILLED after {TIMEOUT_MIN} min"); break
finally:
    proc.wait()

print("-" * 60)
print(f"exit code {proc.returncode} after {(time.time()-t0)/60:.1f} min")
if proc.returncode != 0:
    print("\nLast lines:\n  " + "\n  ".join(tail[-15:]))
elif posteriors:
    print(f"posterior: {posteriors[0]:.1f} -> {posteriors[-1]:.1f} "
          f"({len(posteriors)} samples)")
    print("climbing then plateauing is what you want" if posteriors[-1] > posteriors[0]
          else "posterior did not improve — check the priors")

for f in sorted(XML.parent.glob("*.log")) + sorted(XML.parent.glob("*.trees")):
    print(f"  {f.name:<40} {f.stat().st_size/1024:>9.1f} KB")

beast : /Applications/BEAST 2.7.7/bin/beast
xml   : beast/clade3/H_clade_3.xml
chain : 100,000,000
------------------------------------------------------------
  [     1s]               0    -40116.9357    -39763.1504      -353.7852 --
  [    59s]          100000     -9473.8104     -8702.7133      -771.0970 8m52s/Msamples
  [   113s]          200000     -9309.7187     -8498.6151      -811.1036 9m2s/Msamples
  [   166s]          300000     -9367.5349     -8518.6018      -848.9330 8m55s/Msamples
  [   218s]          400000     -9371.0464     -8523.1108      -847.9355 8m50s/Msamples
  [   270s]          500000     -9303.2826     -8511.9620      -791.3206 8m49s/Msamples
  [   324s]          600000     -9320.8954     -8508.1328      -812.7625 8m50s/Msamples
  [   377s]          700000     -9373.2793     -8534.3051      -838.9742 8m51s/Msamples
  [   432s]          800000     -9365.4560     -8509.3490      -856.1069 8m53s/Msamples
  [   486s]          900000     -9352.6402     -8517.0031      -835.6371 8m53s/Msamples
  [   539s]         1000000     -9318.8743     -8505.9960      -812.8783 8m53s/Msamples
  [   593s]         1100000     -9301.7612     -8505.0551      -796.7060 8m53s/Msamples
  [   647s]         1200000     -9358.7651     -8530.4048      -828.3603 8m54s/Msamples
  [   700s]         1300000     -9326.3290     -8544.7209      -781.6081 8m54s/Msamples
  [   753s]         1400000     -9325.7749     -8500.9590      -824.8158 8m54s/Msamples
  [   807s]         1500000     -9347.1205     -8519.7644      -827.3560 8m54s/Msamples
  [   859s]         1600000     -9323.9508     -8503.1170      -820.8338 8m53s/Msamples
  [   913s]         1700000     -9301.4033     -8505.2739      -796.1294 8m53s/Msamples
  [   966s]         1800000     -9339.1102     -8531.2704      -807.8397 8m53s/Msamples
  [  1021s]         1900000     -9325.3125     -8497.5394      -827.7730 8m54s/Msamples
  [  1075s]         2000000     -9377.0827     -8524.8821      -852.2006 8m54s/Msamples
  [  1129s]         2100000     -9331.1025     -8504.0835      -827.0189 8m54s/Msamples
  [  1184s]         2200000     -9311.2973     -8498.8949      -812.4024 8m55s/Msamples
  [  1239s]         2300000     -9322.2384     -8507.5310      -814.7074 8m56s/Msamples
  [  1292s]         2400000     -9346.9379     -8519.0269      -827.9109 8m56s/Msamples
  [  1346s]         2500000     -9337.9486     -8527.4348      -810.5138 8m56s/Msamples
  [  1400s]         2600000     -9349.1338     -8510.3616      -838.7721 8m56s/Msamples
  [  1454s]         2700000     -9330.3142     -8509.1032      -821.2110 8m56s/Msamples
  [  1508s]         2800000     -9316.3922     -8495.7883      -820.6038 8m56s/Msamples
  [  1564s]         2900000     -9339.4005     -8518.0391      -821.3614 8m57s/Msamples
  [  1618s]         3000000     -9348.3386     -8531.7567      -816.5818 8m57s/Msamples
  [  1672s]         3100000     -9346.0719     -8505.9413      -840.1306 8m57s/Msamples
  [  1725s]         3200000     -9349.0231     -8515.1447      -833.8783 8m57s/Msamples
  [  1779s]         3300000     -9338.7863     -8521.5166      -817.2696 8m57s/Msamples

KILLED after 30 min
------------------------------------------------------------
exit code -9 after 30.1 min

Last lines:
          3210000     -9351.8842     -8515.3115      -836.5726 8m57s/Msamples
          3220000     -9357.8772     -8521.3369      -836.5403 8m57s/Msamples
          3230000     -9382.5972     -8538.8955      -843.7017 8m57s/Msamples
          3240000     -9355.2138     -8502.8539      -852.3599 8m57s/Msamples
          3250000     -9344.3246     -8512.5824      -831.7422 8m57s/Msamples
          3260000     -9330.1254     -8515.1601      -814.9652 8m57s/Msamples
          3270000     -9329.0959     -8508.2422      -820.8537 8m57s/Msamples
          3280000     -9318.2083     -8494.2150      -823.9932 8m57s/Msamples
          3290000     -9336.3896     -8515.6234      -820.7661 8m57s/Msamples
          3300000     -9338.7863     -8521.5166      -817.2696 8m57s/Msamples
          3310000     -9366.0495     -8526.2438      -839.8056 8m57s/Msamples
          3320000     -9353.5547     -8520.2512      -833.3035 8m57s/Msamples
          3330000     -9330.5983     -8512.8225      -817.7758 8m57s/Msamples
          3340000     -9342.9297     -8520.9599      -821.9698 8m57s/Msamples
          3350000     -9335.3022     -8514.6413      -820.6608 8m57s/Msamples
  H_clade_3.log                                133.9 KB
  H_clade_3.trees                             5294.7 KB

In [28]:
from pathlib import Path
import re

d = Path("beast/clade3")   # adjust to where your XML lives
logs = sorted(d.glob("*.log"))
if not logs:
    print("No .log file — BEAST likely never got past initialisation.")
else:
    f = max(logs, key=lambda p: p.stat().st_mtime)
    lines = [l for l in f.read_text().splitlines() if l and not l.startswith("#")]
    data = [l for l in lines[1:] if l.split()[0].isdigit()]
    print(f"{f.name}: {len(data)} samples logged")
    if data:
        last_state = int(data[-1].split()[0])
        mins = 30
        print(f"reached state {last_state:,} in ~{mins} min")
        print(f"rate: {last_state/mins*60:,.0f} states/hour")
        print(f"\n100M states would take {100_000_000/(last_state/mins*60):,.0f} hours "
              f"({100_000_000/(last_state/mins*60)/24:,.1f} days)")
        post = [float(l.split()[1]) for l in data]
        print(f"posterior: {post[0]:.1f} -> {post[-1]:.1f}")
        print("climbing — the chain was working, just slow" if post[-1] > post[0]
              else "flat/erratic — check priors before blaming speed")

H_clade_3.log: 1199 samples logged
reached state 11,980,000 in ~30 min
rate: 23,960,000 states/hour

100M states would take 4 hours (0.2 days)
posterior: -40116.9 -> -9300.3
climbing — the chain was working, just slow

In [29]:
import xml.etree.ElementTree as ET
from pathlib import Path

XML = Path("beast/clade3/H_clade_3.xml")   # <-- the file you actually ran

print("="*66); print(f"  {XML}"); print("="*66)
if not XML.is_file():
    d = XML.parent
    raise FileNotFoundError(f"not found. In {d}: "
        f"{sorted(p.name for p in d.iterdir()) if d.is_dir() else 'dir missing'}")

raw = XML.read_text()
root = ET.fromstring(raw)

for r in root.findall(".//run"):
    cl = r.get("chainLength")
    print(f"chainLength : {int(cl):,}" if cl and cl.isdigit() else f"chainLength : {cl}")

data = root.findall(".//data")
print(f"\ndata partitions : {len(data)}")
for d in data:
    print(f"  id={d.get('id')!r:<30} sequences={len(d.findall('./sequence'))}")

print(f"\ntraitsets : {len(root.findall('.//trait'))}")
for t in root.findall(".//trait"):
    val = t.get("value") or ""
    n = len([v for v in val.split(",") if v.strip()])
    print(f"  traitname={t.get('traitname')!r:<18} entries={n:<5} "
          f"e.g. {val.split(',')[0].strip()[:45]}")

print("\nDISCRETE TRAIT CHECK")
print(f"  'host' appears               : {'host' in raw}")
print(f"  AncestralStateTreeLikelihood : {'AncestralState' in raw}")
print(f"  SVSGeneralSubstitutionModel  : {'SVSGeneralSubstitutionModel' in raw}")
print(f"  BSSVS indicators             : {'indicator' in raw.lower()}")

print("\nLOGGERS")
for lg in root.findall(".//logger"):
    print(f"  {str(lg.get('fileName')):<34} every={lg.get('logEvery'):<8} "
          f"mode={lg.get('mode') or 'params'}")

print("\nVERDICT")
has_dta = len(data) > 1 or "AncestralState" in raw or "SVSGeneralSubstitutionModel" in raw
has_hostlog = any("host" in (lg.get("fileName") or "") for lg in root.findall(".//logger"))
if not has_dta:
    print("  !! NO DISCRETE TRAIT PARTITION — you'd get a timed tree but no")
    print("     host-jump reconstruction, which is the actual result you want.")
if not has_hostlog:
    print("  !! no host.trees logger — ancestral states wouldn't be saved")
if has_dta and has_hostlog:
    print("  complete DTA analysis — ready to run")

==================================================================
  beast/clade3/H_clade_3.xml
==================================================================
chainLength : 100,000,000

data partitions : 1
  id='H_clade_3'                    sequences=162

traitsets : 1
  traitname='date-forward'     entries=162   e.g. KU666057|procyonid|2012.896=2012.8960

DISCRETE TRAIT CHECK
  'host' appears               : False
  AncestralStateTreeLikelihood : False
  SVSGeneralSubstitutionModel  : False
  BSSVS indicators             : False

LOGGERS
  H_clade_3.log                      every=10000    mode=params
  None                               every=10000    mode=params
  H_clade_3.trees                    every=10000    mode=tree

VERDICT
  !! NO DISCRETE TRAIT PARTITION — you'd get a timed tree but no
     host-jump reconstruction, which is the actual result you want.
  !! no host.trees logger — ancestral states wouldn't be saved

In [30]:
from pathlib import Path
import xml.etree.ElementTree as ET

XML = Path("beast/clade3/clade3_dta.xml")
raw = XML.read_text()
root = ET.fromstring(raw)

print(f"data partitions : {len(root.findall('.//data'))}")
for r in root.findall(".//run"):
    cl = r.get("chainLength")
    print(f"chainLength     : {int(cl):,}" if cl and cl.isdigit() else f"chainLength : {cl}")
print(f"BSSVS indicators: {'indicator' in raw.lower()}")
print(f"asymmetric model: {'SVSGeneralSubstitutionModel' in raw or 'AncestralState' in raw}")
print("\nloggers:")
for lg in root.findall(".//logger"):
    print(f"  {str(lg.get('fileName')):<34} every={lg.get('logEvery')}")

FileNotFoundError: [Errno 2] No such file or directory: 'beast/clade3/clade3_dta.xml'

In [31]:
from pathlib import Path
import time

hits = [p for p in Path.home().rglob("*.xml")
        if "dta" in p.name.lower() or "clade3" in p.name.lower()]
hits.sort(key=lambda p: p.stat().st_mtime, reverse=True)

for p in hits[:10]:
    age = (time.time() - p.stat().st_mtime) / 60
    print(f"{age:7.1f} min ago  {p.stat().st_size/1024:8.1f} KB  {p}")

    2.0 min ago     365.7 KB  /Users/batyanightingale/projects/cdv-phylodynamics/data/beast:clade3:clade3_dta.xml
  291.7 min ago     353.7 KB  /Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/H_clade_3_dta.xml

In [34]:
import shutil
src = Path(Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3_dta.xml)
dst = Path(Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/clade3_dta.xml)
dst.parent.mkdir(parents=True, exist_ok=True)
shutil.move(str(src), dst)
print("now at", dst.resolve())

NameError: name 'Users' is not defined

In [35]:
import shutil
from pathlib import Path

src = Path("/Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3_dta.xml")
dst = Path("/Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/clade3_dta.xml")
dst.parent.mkdir(parents=True, exist_ok=True)
shutil.move(str(src), str(dst))
print("now at", dst.resolve())

now at /Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/clade3_dta.xml

In [36]:
XML = Path("beast/clade3/clade3_dta.xml")

In [37]:
from pathlib import Path
import xml.etree.ElementTree as ET

XML = Path("beast/clade3/clade3_dta.xml")
raw = XML.read_text()
root = ET.fromstring(raw)

data = root.findall(".//data")
print(f"data partitions : {len(data)}")
for d in data:
    print(f"    id={d.get('id')!r:<28} sequences={len(d.findall('./sequence'))}")

for r in root.findall(".//run"):
    cl = r.get("chainLength")
    print(f"chainLength     : {int(cl):,}" if cl and cl.isdigit() else f"chainLength : {cl}")

print(f"BSSVS indicators: {'indicator' in raw.lower()}")
print(f"trait model     : {'SVSGeneralSubstitutionModel' in raw or 'AncestralState' in raw}")

print("\nloggers:")
for lg in root.findall(".//logger"):
    print(f"    {str(lg.get('fileName')):<34} every={lg.get('logEvery')}")

ok = len(data) >= 2 and any("host" in (lg.get("fileName") or "") for lg in root.findall(".//logger"))
print("\n" + ("READY — trait partition and host logger both present" if ok
              else "NOT READY — see above"))

data partitions : 2
    id='H_clade_3'                  sequences=162
    id='Host'                       sequences=0
chainLength     : 10,000,000
BSSVS indicators: True
trait model     : True

loggers:
    clade3_dta.log                     every=10000
    None                               every=1000
    clade3_dta.trees                   every=1000
    Host_tree_with_trait.trees         every=10000

NOT READY — see above

In [38]:
import re, shutil
import xml.etree.ElementTree as ET
from pathlib import Path

XML       = Path("beast/clade3/clade3_dta.xml")
CHAIN     = 10_000_000    # keep 10M; raise later only if ESS falls short
LOG_EVERY = 10_000

backup = XML.with_suffix(".xml.bak")
shutil.copy(XML, backup)
print(f"backup -> {backup.name}\n")

raw = XML.read_text()

raw, n_chain = re.subn(r'(<run\b[^>]*?chainLength=")\d+(")',
                       rf'\g<1>{CHAIN}\g<2>', raw)

def fix_logger(m):
    tag = m.group(0)
    if 'id="screenlog"' in tag:        # leave console output alone
        return tag
    return re.sub(r'logEvery="\d+"', f'logEvery="{LOG_EVERY}"', tag)

raw, n_log = re.subn(r'<logger\b[^>]*>', fix_logger, raw)
XML.write_text(raw)

# verify
root = ET.fromstring(XML.read_text())
for r in root.findall(".//run"):
    print(f"chainLength : {int(r.get('chainLength')):,}")
print("\nloggers:")
for lg in root.findall(".//logger"):
    print(f"  {str(lg.get('fileName')):<34} every={lg.get('logEvery')}")

samples = CHAIN // LOG_EVERY
print(f"\n{samples} samples per file — {'good' if samples >= 500 else 'thin, lower LOG_EVERY'}")
print(f"chain edits: {n_chain} | loggers scanned: {n_log}")

backup -> clade3_dta.xml.bak

chainLength : 10,000,000

loggers:
  clade3_dta.log                     every=10000
  None                               every=1000
  clade3_dta.trees                   every=10000
  Host_tree_with_trait.trees         every=10000

1000 samples per file — good
chain edits: 1 | loggers scanned: 4

In [39]:
import shutil, subprocess, time, re
from pathlib import Path

XML         = Path("beast/clade3/clade3_dta.xml")
SEED        = 12345
THREADS     = 4
TIMEOUT_MIN = 90

def find_beast():
    exe = shutil.which("beast")
    if exe:
        return exe
    for root in [Path("/Applications"), Path.home() / "Applications", Path.home()]:
        if root.is_dir():
            for pattern in ("BEAST*/bin/beast", "*/BEAST*/bin/beast"):
                hits = sorted(root.glob(pattern))
                if hits:
                    return str(hits[0])
    return None

beast = find_beast()
if not beast:
    raise RuntimeError("BEAST not found. Set `beast` to the full path of BEAST*/bin/beast")
if not XML.is_file():
    d = XML.parent
    raise FileNotFoundError(f"{XML} missing. In {d}: "
        f"{sorted(p.name for p in d.iterdir()) if d.is_dir() else 'dir missing'}")

chain = re.search(r'chainLength="(\d+)"', XML.read_text())
print(f"beast : {beast}")
print(f"xml   : {XML}")
print(f"chain : {int(chain.group(1)):,}" if chain else "chain : ?")
print(f"seed  : {SEED}")
print("-"*66)

cmd = [beast, "-seed", str(SEED), "-threads", str(THREADS), "-overwrite", str(XML)]
t0 = time.time()
proc = subprocess.Popen(cmd, cwd=XML.parent, stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT, text=True, bufsize=1)
posteriors, tail, n = [], [], 0
try:
    for line in proc.stdout:
        line = line.rstrip(); tail.append(line); tail[:] = tail[-40:]
        low = line.lower()
        if any(k in low for k in ("state", "trait", "beagle", "error", "exception")) and n < 25:
            print(f"  {line[:100]}"); n += 1
        parts = line.split()
        if len(parts) >= 2 and parts[0].isdigit():
            try:
                posteriors.append(float(parts[1]))
                if len(posteriors) % 25 == 1:
                    el = time.time() - t0
                    frac = int(parts[0]) / int(chain.group(1)) if chain else 0
                    eta = (el/frac - el)/60 if frac > 0.01 else 0
                    print(f"  [{el/60:5.1f} min] state {int(parts[0]):>12,}  "
                          f"posterior {parts[1]:>12}  ETA {eta:5.1f} min")
            except ValueError:
                pass
        if time.time() - t0 > TIMEOUT_MIN*60:
            proc.kill(); print(f"\nKILLED at {TIMEOUT_MIN} min"); break
finally:
    proc.wait()

print("-"*66)
print(f"exit {proc.returncode} after {(time.time()-t0)/60:.1f} min")
if proc.returncode != 0:
    print("\nlast lines:\n  " + "\n  ".join(tail[-15:]))
elif posteriors:
    print(f"posterior {posteriors[0]:,.1f} -> {posteriors[-1]:,.1f}")

print("\noutput files:")
for f in sorted(XML.parent.glob("*.log")) + sorted(XML.parent.glob("*.trees")):
    kb = f.stat().st_size/1024
    flag = "  <-- EMPTY" if kb < 1 else ""
    print(f"  {f.name:<38} {kb:>10.1f} KB{flag}")

beast : /Applications/BEAST 2.7.7/bin/beast
xml   : beast/clade3/clade3_dta.xml
chain : 10,000,000
seed  : 12345
------------------------------------------------------------------
  java.io.FileNotFoundException: /Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/beast
------------------------------------------------------------------
exit 1 after 0.0 min

last lines:
  java.io.FileNotFoundException: /Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/beast/clade3/clade3_dta.xml (No such file or directory)
  	at java.base/java.io.FileInputStream.open0(Native Method)
  	at java.base/java.io.FileInputStream.open(Unknown Source)
  	at java.base/java.io.FileInputStream.<init>(Unknown Source)
  	at java.base/java.io.FileReader.<init>(Unknown Source)
  	at beast.base.util.FileUtils.load(Unknown Source)
  	at beast.base.parser.XMLParser.parseFile(Unknown Source)
  	at beastfx.app.beast.BeastMCMC.parseArgs(Unknown Source)
  	at beastfx.app.beast.BeastMain.main(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  	at beast.pkgmgmt.launcher.BeastLauncher.run(Unknown Source)
  	at beast.pkgmgmt.launcher.BeastLauncher.main(Unknown Source)

output files:
  H_clade_3.log                               448.7 KB
  H_clade_3.trees                           18850.4 KB

In [40]:
import shutil, subprocess, time, re
from pathlib import Path

XML         = Path("beast/clade3/clade3_dta.xml").resolve()   # absolute: fixes the doubled path
SEED        = 12345
THREADS     = 4
TIMEOUT_MIN = 90

# --- move the old sequence-only outputs aside ---
for f in ["H_clade_3.log", "H_clade_3.trees"]:
    p = XML.parent / f
    if p.exists():
        p.rename(XML.parent / ("OLD_seqonly_" + f))
        print(f"renamed {f} -> OLD_seqonly_{f}")

def find_beast():
    exe = shutil.which("beast")
    if exe:
        return exe
    for root in [Path("/Applications"), Path.home() / "Applications", Path.home()]:
        if root.is_dir():
            for pattern in ("BEAST*/bin/beast", "*/BEAST*/bin/beast"):
                hits = sorted(root.glob(pattern))
                if hits:
                    return str(hits[0])
    return None

beast = find_beast()
if not beast:
    raise RuntimeError("BEAST not found — set `beast` to the full path of BEAST*/bin/beast")
if not XML.is_file():
    raise FileNotFoundError(f"{XML} missing")

chain = re.search(r'chainLength="(\d+)"', XML.read_text())
total = int(chain.group(1)) if chain else None
print(f"\nbeast : {beast}")
print(f"xml   : {XML}")
print(f"chain : {total:,}" if total else "chain : ?")
print(f"seed  : {SEED}")
print("-"*66)

cmd = [beast, "-seed", str(SEED), "-threads", str(THREADS), "-overwrite", str(XML)]
t0 = time.time()
proc = subprocess.Popen(cmd, cwd=str(XML.parent), stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT, text=True, bufsize=1)
posteriors, tail, shown = [], [], 0
try:
    for line in proc.stdout:
        line = line.rstrip(); tail.append(line); tail[:] = tail[-40:]
        low = line.lower()
        if any(k in low for k in ("trait", "beagle", "error", "exception", "states")) and shown < 25:
            print(f"  {line[:100]}"); shown += 1
        parts = line.split()
        if len(parts) >= 2 and parts[0].isdigit():
            try:
                posteriors.append(float(parts[1]))
                if len(posteriors) % 25 == 1 and total:
                    el = time.time() - t0
                    frac = int(parts[0]) / total
                    eta = (el/frac - el)/60 if frac > 0.01 else 0
                    print(f"  [{el/60:5.1f} min] state {int(parts[0]):>12,}  "
                          f"posterior {parts[1]:>12}  ETA {eta:5.1f} min")
            except ValueError:
                pass
        if time.time() - t0 > TIMEOUT_MIN*60:
            proc.kill(); print(f"\nKILLED at {TIMEOUT_MIN} min"); break
finally:
    proc.wait()

print("-"*66)
print(f"exit {proc.returncode} after {(time.time()-t0)/60:.1f} min")
if proc.returncode != 0:
    print("\nlast lines:\n  " + "\n  ".join(tail[-15:]))
elif posteriors:
    print(f"posterior {posteriors[0]:,.1f} -> {posteriors[-1]:,.1f}")

print("\noutput files:")
for f in sorted(XML.parent.glob("clade3_dta*")) + sorted(XML.parent.glob("Host*")):
    kb = f.stat().st_size/1024
    print(f"  {f.name:<40} {kb:>10.1f} KB" + ("   <-- EMPTY" if kb < 1 else ""))

renamed H_clade_3.log -> OLD_seqonly_H_clade_3.log
renamed H_clade_3.trees -> OLD_seqonly_H_clade_3.trees

beast : /Applications/BEAST 2.7.7/bin/beast
xml   : /Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/clade3_dta.xml
chain : 10,000,000
seed  : 12345
------------------------------------------------------------------
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  AncestralStateTreeLikelihood(traitedtreeLikelihood.Host) uses BeerLikelihoodCore
    AlignmentFromTrait(Host): [taxa, patterns, sites] = [162, 1, 1]
  Writing file Host_tree_with_trait.trees
  [  0.0 min] state            0  posterior  -39016.5610  ETA   0.0 min
  [  0.2 min] state       25,000  posterior  -14000.3654  ETA   0.0 min
  [  0.4 min] state       50,000  posterior  -12115.3237  ETA   0.0 min
  [  0.6 min] state       75,000  posterior  -11291.6615  ETA   0.0 min
  [  0.8 min] state      100,000  posterior  -11103.0492  ETA   0.0 min
  [  0.9 min] state      125,000  posterior  -10791.9447  ETA  74.0 min
  [  1.1 min] state      150,000  posterior  -10571.8024  ETA  71.8 min
  [  1.2 min] state      175,000  posterior  -10417.5737  ETA  70.1 min
  [  1.4 min] state      200,000  posterior  -10277.3043  ETA  68.9 min
  [  1.6 min] state      225,000  posterior   -9974.4039  ETA  68.8 min
  [  1.7 min] state      250,000  posterior   -9655.9087  ETA  67.9 min
  [  1.9 min] state      275,000  posterior   -9540.9650  ETA  67.2 min
  [  2.1 min] state            0  posterior          NaN  ETA   0.0 min
  java.lang.Error: randomChoiceUnnormalized falls through -- negative components in input distribution
  Please report error to Marc
  [  2.2 min] state      319,000  posterior   -9552.9466  ETA  66.1 min
  [  2.3 min] state      344,000  posterior   -9519.2012  ETA  65.6 min
  java.lang.Error: randomChoiceUnnormalized falls through -- negative components in input distribution
  Please report error to Marc
  [  2.5 min] state      363,000  posterior   -9553.9079  ETA  65.2 min
  java.lang.reflect.InvocationTargetException
  Caused by: java.lang.Error: randomChoiceUnnormalized falls through -- negative components in input d
  	at beastclassic.evolution.likelihood.AncestralStateTreeLikelihood.redrawAncestralStates(Unknown Sou
  	at beastclassic.evolution.likelihood.AncestralStateTreeLikelihood.getStatesForNode(Unknown Source)
  	at beastclassic.evolution.likelihood.AncestralStateTreeLikelihood$1.getTraitString(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.log(Unknown Source)

KeyboardInterrupt:

In [41]:
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path
import shutil

XML   = Path("beast/clade3/clade3_dta.xml").resolve()
OUT   = XML.parent / "clade3_dta_merged.xml"
REMAP = {"ailurid": "wild_felid"}      # single-sequence state folded in

raw  = XML.read_text()
root = ET.fromstring(raw)

for el in root.iter():
    tn, val = el.get("traitname"), el.get("value")
    if not val or not tn or tn == "date-forward":
        continue
    pairs = [p for p in val.split(",") if "=" in p]
    print(f"traitname={tn!r} — {len(pairs)} taxa")
    print("  before:", dict(Counter(p.rsplit('=',1)[1].strip() for p in pairs)))
    new_pairs = [f"{p.rsplit('=',1)[0]}={REMAP.get(p.rsplit('=',1)[1].strip(), p.rsplit('=',1)[1].strip())}"
                 for p in pairs]
    print("  after :", dict(Counter(p.rsplit('=',1)[1] for p in new_pairs)))
    raw = raw.replace(val, ",".join(new_pairs))

ET.fromstring(raw)          # fails loudly if the edit broke anything
OUT.write_text(raw)
print(f"\nwrote {OUT.name}")

traitname='date' — 162 taxa
  before: {'2012.896': 1, '2019.312': 1, '1992.787': 1, '1992.667': 1, '1992.000': 1, '2013.268': 1, '2013.230': 1, '2013.238': 1, '2013.164': 1, '2013.195': 1, '2004.675': 1, '2019.304': 1, '2015.964': 1, '2015.989': 1, '2015.912': 1, '2015.951': 2, '2016.322': 1, '2016.336': 1, '2016.301': 1, '2017.660': 1, '2016.973': 2, '2017.301': 1, '2017.167': 1, '2016.210': 1, '2023.030': 1, '2022.819': 1, '2022.805': 1, '2023.392': 1, '2016.361': 1, '2022.926': 1, '2013.748': 1, '2017.970': 1, '2021.041': 1, '2023.622': 1, '2016.500': 28, '2017.500': 27, '2004.500': 2, '2007.500': 3, '2018.500': 1, '2010.500': 2, '2014.500': 29, '2013.500': 10, '2012.500': 1, '2015.500': 23}
  after : {'2012.896': 1, '2019.312': 1, '1992.787': 1, '1992.667': 1, '1992.000': 1, '2013.268': 1, '2013.230': 1, '2013.238': 1, '2013.164': 1, '2013.195': 1, '2004.675': 1, '2019.304': 1, '2015.964': 1, '2015.989': 1, '2015.912': 1, '2015.951': 2, '2016.322': 1, '2016.336': 1, '2016.301': 1, '2017.660': 1, '2016.973': 2, '2017.301': 1, '2017.167': 1, '2016.210': 1, '2023.030': 1, '2022.819': 1, '2022.805': 1, '2023.392': 1, '2016.361': 1, '2022.926': 1, '2013.748': 1, '2017.970': 1, '2021.041': 1, '2023.622': 1, '2016.500': 28, '2017.500': 27, '2004.500': 2, '2007.500': 3, '2018.500': 1, '2010.500': 2, '2014.500': 29, '2013.500': 10, '2012.500': 1, '2015.500': 23}

wrote clade3_dta_merged.xml

In [42]:
import shutil, subprocess, time, re
from pathlib import Path

XML         = Path("beast/clade3/clade3_dta_merged.xml").resolve()
SEED        = 12345
THREADS     = 4
TIMEOUT_MIN = 120

# park the outputs from the crashed run — Host_tree_with_trait.trees is corrupt
crashed = XML.parent / "crashed_run"
moved = []
for f in XML.parent.glob("*"):
    if f.is_file() and (f.name.startswith("clade3_dta.") and f.suffix in (".log", ".trees")
                        or f.name.startswith("Host_tree_with_trait")):
        crashed.mkdir(exist_ok=True)
        shutil.move(str(f), crashed / f.name)
        moved.append(f.name)
print(f"moved to crashed_run/: {moved}" if moved else "no previous outputs to move")

def find_beast():
    exe = shutil.which("beast")
    if exe:
        return exe
    for root in [Path("/Applications"), Path.home() / "Applications", Path.home()]:
        if root.is_dir():
            for pattern in ("BEAST*/bin/beast", "*/BEAST*/bin/beast"):
                hits = sorted(root.glob(pattern))
                if hits:
                    return str(hits[0])
    return None

beast = find_beast()
if not beast:
    raise RuntimeError("BEAST not found")
if not XML.is_file():
    raise FileNotFoundError(f"{XML} missing — run the remap cell first")

chain = re.search(r'chainLength="(\d+)"', XML.read_text())
total = int(chain.group(1)) if chain else None
print(f"\nbeast : {beast}")
print(f"xml   : {XML.name}")
print(f"chain : {total:,}" if total else "chain : ?")
print("-"*66)

cmd = [beast, "-seed", str(SEED), "-threads", str(THREADS), "-overwrite", str(XML)]
t0 = time.time()
proc = subprocess.Popen(cmd, cwd=str(XML.parent), stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT, text=True, bufsize=1)
posteriors, tail, shown, errors = [], [], 0, 0
try:
    for line in proc.stdout:
        line = line.rstrip(); tail.append(line); tail[:] = tail[-40:]
        low = line.lower()
        if "randomchoiceunnormalized" in low or "java.lang.Error" in line:
            errors += 1
            if errors <= 3:
                print(f"  !! {line[:100]}")
            if errors == 4:
                print("  !! still crashing — kill this and switch to a symmetric trait model")
        elif any(k in low for k in ("trait", "beagle", "states", "writing file")) and shown < 20:
            print(f"  {line[:100]}"); shown += 1
        parts = line.split()
        if len(parts) >= 2 and parts[0].isdigit():
            try:
                posteriors.append(float(parts[1]))
                if len(posteriors) % 25 == 1 and total:
                    el = time.time() - t0
                    frac = int(parts[0]) / total
                    eta = (el/frac - el)/60 if frac > 0.01 else 0
                    print(f"  [{el/60:5.1f} min] state {int(parts[0]):>12,}  "
                          f"posterior {parts[1]:>12}  ETA {eta:5.1f} min")
            except ValueError:
                pass
        if time.time() - t0 > TIMEOUT_MIN*60:
            proc.kill(); print(f"\nKILLED at {TIMEOUT_MIN} min"); break
finally:
    proc.wait()

print("-"*66)
print(f"exit {proc.returncode} after {(time.time()-t0)/60:.1f} min | trait errors: {errors}")
if proc.returncode != 0:
    print("\nlast lines:\n  " + "\n  ".join(tail[-12:]))
elif posteriors:
    print(f"posterior {posteriors[0]:,.1f} -> {posteriors[-1]:,.1f}")

print("\noutput files:")
for f in sorted(XML.parent.glob("*.log")) + sorted(XML.parent.glob("*.trees")):
    kb = f.stat().st_size/1024
    print(f"  {f.name:<40} {kb:>10.1f} KB" + ("   <-- EMPTY" if kb < 1 else ""))

moved to crashed_run/: ['clade3_dta.trees', 'clade3_dta.log', 'Host_tree_with_trait.trees']

beast : /Applications/BEAST 2.7.7/bin/beast
xml   : clade3_dta_merged.xml
chain : 10,000,000
------------------------------------------------------------------
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  AncestralStateTreeLikelihood(traitedtreeLikelihood.Host) uses BeerLikelihoodCore
    AlignmentFromTrait(Host): [taxa, patterns, sites] = [162, 1, 1]
  Writing file clade3_dta.log
  Writing file clade3_dta.trees
  Writing file Host_tree_with_trait.trees
  [  0.0 min] state            0  posterior  -39016.5610  ETA   0.0 min
  [  0.2 min] state       25,000  posterior  -14000.3654  ETA   0.0 min
  [  0.3 min] state       50,000  posterior  -12115.3237  ETA   0.0 min
  [  0.5 min] state       75,000  posterior  -11291.6615  ETA   0.0 min
  [  0.6 min] state      100,000  posterior  -11103.0492  ETA   0.0 min
  [  0.7 min] state      125,000  posterior  -10791.9447  ETA  58.4 min
  [  0.9 min] state      150,000  posterior  -10571.8024  ETA  57.5 min
  [  1.0 min] state      175,000  posterior  -10417.5737  ETA  56.7 min
  [  1.1 min] state      200,000  posterior  -10277.3043  ETA  56.1 min
  [  1.3 min] state      225,000  posterior   -9974.4039  ETA  55.6 min
  [  1.4 min] state      250,000  posterior   -9655.9087  ETA  55.0 min
  [  1.5 min] state      275,000  posterior   -9540.9650  ETA  54.7 min
  [  1.7 min] state            0  posterior          NaN  ETA   0.0 min
  !! java.lang.Error: randomChoiceUnnormalized falls through -- negative components in input distribution
  [  1.8 min] state      319,000  posterior   -9552.9466  ETA  54.0 min
  [  1.9 min] state      344,000  posterior   -9519.2012  ETA  53.6 min
  !! java.lang.Error: randomChoiceUnnormalized falls through -- negative components in input distribution
  [  2.0 min] state      363,000  posterior   -9553.9079  ETA  53.4 min
  !! Caused by: java.lang.Error: randomChoiceUnnormalized falls through -- negative components in input d
  	at beastclassic.evolution.likelihood.AncestralStateTreeLikelihood.redrawAncestralStates(Unknown Sou
  	at beastclassic.evolution.likelihood.AncestralStateTreeLikelihood.getStatesForNode(Unknown Source)
  	at beastclassic.evolution.likelihood.AncestralStateTreeLikelihood$1.getTraitString(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)

KeyboardInterrupt:

In [43]:
from pathlib import Path
import hashlib, re
from collections import Counter

d = Path("beast/clade3")
for name in ["clade3_dta.xml", "clade3_dta_merged.xml"]:
    p = d / name
    raw = p.read_text()
    print(f"{name}: {hashlib.md5(raw.encode()).hexdigest()[:12]}  {len(raw):,} chars")
    print("   ailurid occurrences:", raw.count("ailurid"))

# where do the trait states actually live?
raw = (d / "clade3_dta.xml").read_text()
for m in re.finditer(r'<(\w+)[^>]*traitname="([^"]+)"', raw):
    print(f"\nelement <{m.group(1)}> traitname={m.group(2)!r}")

clade3_dta.xml: 8212e81f8433  374,522 chars
   ailurid occurrences: 6
clade3_dta_merged.xml: 8212e81f8433  374,522 chars
   ailurid occurrences: 6

element <trait> traitname='date'

element <traitSet> traitname='discrete'

In [44]:
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

XML   = Path("beast/clade3/clade3_dta.xml").resolve()
OUT   = XML.parent / "clade3_dta_merged.xml"
REMAP = {"ailurid": "wild_felid"}

tree = ET.parse(XML); root = tree.getroot()
changed = 0
for el in root.iter():
    tn = el.get("traitname")
    if not tn or tn.startswith("date"):
        continue
    src = "attr" if el.get("value") else "text"
    val = el.get("value") or (el.text or "")
    pairs = [x.strip() for x in val.replace("\n", " ").split(",") if "=" in x]
    if not pairs:
        continue
    print(f"<{el.tag}> traitname={tn!r} source={src} taxa={len(pairs)}")
    print("  before:", dict(Counter(x.rsplit('=',1)[1].strip() for x in pairs)))
    new = [f"{x.rsplit('=',1)[0].strip()}="
           f"{REMAP.get(x.rsplit('=',1)[1].strip(), x.rsplit('=',1)[1].strip())}" for x in pairs]
    print("  after :", dict(Counter(x.rsplit('=',1)[1] for x in new)))
    if src == "attr":
        el.set("value", ",".join(new))
    else:
        el.text = "\n" + ",\n".join(new) + "\n"
    changed += 1

if not changed:
    raise RuntimeError("no discrete traitset found — paste me the <traitSet> block")
tree.write(OUT, encoding="unicode", xml_declaration=True)
print(f"\nchanged {changed} element(s) -> {OUT.name}")
print("ailurid remaining:", OUT.read_text().count("=ailurid"))

<traitSet> traitname='discrete' source=text taxa=162
  before: {'procyonid': 91, 'wild_felid': 7, 'wild_canid': 32, 'domestic_dog': 8, 'mustelid': 23, 'ailurid': 1}
  after : {'procyonid': 91, 'wild_felid': 8, 'wild_canid': 32, 'domestic_dog': 8, 'mustelid': 23}

changed 1 element(s) -> clade3_dta_merged.xml
ailurid remaining: 0

In [45]:
from pathlib import Path
import xml.etree.ElementTree as ET
p = Path("beast/clade3/clade3_dta_merged.xml")
r = ET.fromstring(p.read_text())
print("data partitions:", len(r.findall(".//data")))
print("chainLength   :", [x.get("chainLength") for x in r.findall(".//run")])
print("loggers       :", [x.get("fileName") for x in r.findall(".//logger")])
print("BSSVS         :", "indicator" in p.read_text().lower())

data partitions: 2
chainLength   : ['10000000']
loggers       : ['clade3_dta.log', None, 'clade3_dta.trees', 'Host_tree_with_trait.trees']
BSSVS         : True

In [46]:
XML = Path("beast/clade3/clade3_dta_merged.xml").resolve()

In [47]:
import shutil, subprocess, time, re
from pathlib import Path

XML         = Path("beast/clade3/clade3_dta_merged.xml").resolve()
SEED        = 12345
THREADS     = 4
TIMEOUT_MIN = 120

# park outputs from the previous crashed attempt
crashed = XML.parent / "crashed_run2"
moved = []
for f in XML.parent.glob("*"):
    if f.is_file() and (f.name.startswith("clade3_dta.") and f.suffix in (".log", ".trees")
                        or f.name.startswith("Host_tree_with_trait")):
        crashed.mkdir(exist_ok=True)
        shutil.move(str(f), crashed / f.name)
        moved.append(f.name)
print(f"moved aside: {moved}" if moved else "no previous outputs to move")

def find_beast():
    exe = shutil.which("beast")
    if exe:
        return exe
    for root in [Path("/Applications"), Path.home() / "Applications", Path.home()]:
        if root.is_dir():
            for pattern in ("BEAST*/bin/beast", "*/BEAST*/bin/beast"):
                hits = sorted(root.glob(pattern))
                if hits:
                    return str(hits[0])
    return None

beast = find_beast()
if not beast:
    raise RuntimeError("BEAST not found")
if not XML.is_file():
    raise FileNotFoundError(f"{XML} missing — run the remap cell first")

chain = re.search(r'chainLength="(\d+)"', XML.read_text())
total = int(chain.group(1)) if chain else None
print(f"\nbeast : {beast}")
print(f"xml   : {XML.name}")
print(f"chain : {total:,}" if total else "chain : ?")
print("-"*66)

cmd = [beast, "-seed", str(SEED), "-threads", str(THREADS), "-overwrite", str(XML)]
t0 = time.time()
proc = subprocess.Popen(cmd, cwd=str(XML.parent), stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT, text=True, bufsize=1)
posteriors, tail, shown, errors = [], [], 0, 0
passed_500k = False
try:
    for line in proc.stdout:
        line = line.rstrip(); tail.append(line); tail[:] = tail[-40:]
        low = line.lower()
        if "randomchoiceunnormalized" in low:
            errors += 1
            if errors <= 3:
                print(f"  !! trait error {errors} — {line[:80]}")
            if errors == 4:
                print("  !! SAME CRASH — kill this. Untick BSSVS in BEAUti, set Symmetric.")
        elif any(k in low for k in ("trait", "beagle", "states", "writing file")) and shown < 18:
            print(f"  {line[:100]}"); shown += 1
        parts = line.split()
        if len(parts) >= 2 and parts[0].isdigit():
            state = int(parts[0])
            if state > 500_000 and not passed_500k and errors == 0:
                passed_500k = True
                print("  >> past 500,000 states with no trait errors — the merge fixed it")
            try:
                posteriors.append(float(parts[1]))
                if len(posteriors) % 25 == 1 and total:
                    el = time.time() - t0
                    frac = state / total
                    eta = (el/frac - el)/60 if frac > 0.01 else 0
                    print(f"  [{el/60:5.1f} min] state {state:>12,}  "
                          f"posterior {parts[1]:>12}  ETA {eta:5.1f} min")
            except ValueError:
                pass
        if time.time() - t0 > TIMEOUT_MIN*60:
            proc.kill(); print(f"\nKILLED at {TIMEOUT_MIN} min"); break
finally:
    proc.wait()

print("-"*66)
print(f"exit {proc.returncode} after {(time.time()-t0)/60:.1f} min | trait errors: {errors}")
if proc.returncode != 0:
    print("\nlast lines:\n  " + "\n  ".join(tail[-12:]))
elif posteriors:
    print(f"posterior {posteriors[0]:,.1f} -> {posteriors[-1]:,.1f}")

print("\noutput files:")
for f in sorted(XML.parent.glob("*.log")) + sorted(XML.parent.glob("*.trees")):
    kb = f.stat().st_size/1024
    print(f"  {f.name:<40} {kb:>10.1f} KB" + ("   <-- EMPTY" if kb < 1 else ""))

moved aside: ['clade3_dta.trees', 'clade3_dta.log', 'Host_tree_with_trait.trees']

beast : /Applications/BEAST 2.7.7/bin/beast
xml   : clade3_dta_merged.xml
chain : 10,000,000
------------------------------------------------------------------
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /usr/local/lib:/Applications/B
  AncestralStateTreeLikelihood(traitedtreeLikelihood.Host) uses BeerLikelihoodCore
    AlignmentFromTrait(Host): [taxa, patterns, sites] = [162, 1, 1]
  Writing file clade3_dta.log
  Writing file clade3_dta.trees
  Writing file Host_tree_with_trait.trees
  [  0.0 min] state            0  posterior  -39016.5595  ETA   0.0 min
  [  0.2 min] state       25,000  posterior  -13898.1616  ETA   0.0 min
  [  0.3 min] state       50,000  posterior  -11980.5256  ETA   0.0 min
  [  0.5 min] state       75,000  posterior  -10857.3948  ETA   0.0 min
  [  0.6 min] state      100,000  posterior  -10419.2804  ETA   0.0 min
  [  0.7 min] state      125,000  posterior  -10050.2166  ETA  58.8 min
  [  0.9 min] state      150,000  posterior   -9994.7117  ETA  57.8 min
  [  1.0 min] state      175,000  posterior   -9884.3847  ETA  56.9 min
  [  1.2 min] state      200,000  posterior   -9808.4698  ETA  56.4 min
  [  1.3 min] state      225,000  posterior   -9783.0877  ETA  55.8 min
  [  1.4 min] state      250,000  posterior   -9648.2560  ETA  55.2 min
  [  1.5 min] state      275,000  posterior   -9612.2289  ETA  54.6 min
  [  1.7 min] state      300,000  posterior   -9541.9410  ETA  54.1 min
  [  1.8 min] state      325,000  posterior   -9550.6098  ETA  53.5 min
  [  1.9 min] state      350,000  posterior   -9510.8943  ETA  53.0 min
  [  2.1 min] state      375,000  posterior   -9535.0101  ETA  52.7 min
  [  2.2 min] state      400,000  posterior   -9541.4795  ETA  52.5 min
  [  2.3 min] state      425,000  posterior   -9551.0374  ETA  52.3 min
  [  2.5 min] state      450,000  posterior   -9558.2781  ETA  52.0 min
  [  2.6 min] state      475,000  posterior   -9553.2450  ETA  51.7 min
  [  2.7 min] state      500,000  posterior   -9547.9679  ETA  51.4 min
  >> past 500,000 states with no trait errors — the merge fixed it
  [  2.8 min] state      525,000  posterior   -9511.4175  ETA  51.1 min
  [  3.0 min] state      550,000  posterior   -9509.5758  ETA  50.8 min
  [  3.1 min] state      575,000  posterior   -9522.7410  ETA  50.5 min
  [  3.2 min] state      600,000  posterior   -9526.1443  ETA  50.3 min
  [  3.3 min] state      625,000  posterior   -9561.5332  ETA  50.2 min
  [  3.5 min] state      650,000  posterior   -9572.7112  ETA  50.1 min
  [  3.6 min] state      675,000  posterior   -9599.4782  ETA  49.8 min
  [  3.7 min] state      700,000  posterior   -9557.6646  ETA  49.6 min
  [  3.9 min] state      725,000  posterior   -9542.0310  ETA  49.4 min
  [  4.0 min] state      750,000  posterior   -9529.3527  ETA  49.2 min
  [  4.1 min] state      775,000  posterior   -9540.6165  ETA  49.1 min
  [  4.3 min] state      800,000  posterior   -9554.6303  ETA  48.9 min
  [  4.4 min] state      825,000  posterior   -9576.2229  ETA  48.7 min
  [  4.5 min] state      850,000  posterior   -9577.4034  ETA  48.4 min
  [  4.6 min] state      875,000  posterior   -9563.7962  ETA  48.2 min
  [  4.7 min] state      900,000  posterior   -9567.3250  ETA  48.0 min
  [  4.9 min] state      925,000  posterior   -9516.8454  ETA  47.8 min
  [  5.0 min] state      950,000  posterior   -9519.2167  ETA  47.7 min
  [  5.1 min] state      975,000  posterior   -9533.2274  ETA  47.5 min
  [  5.3 min] state    1,000,000  posterior   -9561.9882  ETA  47.3 min
  [  5.4 min] state    1,025,000  posterior   -9569.9832  ETA  47.2 min
  [  5.5 min] state    1,050,000  posterior   -9552.1602  ETA  47.0 min
  [  5.6 min] state    1,075,000  posterior   -9530.6088  ETA  46.8 min
  [  5.8 min] state    1,100,000  posterior   -9527.8834  ETA  46.7 min
  [  5.9 min] state    1,125,000  posterior   -9486.0154  ETA  46.5 min
  [  6.0 min] state    1,150,000  posterior   -9520.3469  ETA  46.4 min
  [  6.2 min] state    1,175,000  posterior   -9518.2202  ETA  46.2 min
  [  6.3 min] state    1,200,000  posterior   -9553.9101  ETA  46.0 min
  [  6.4 min] state            5  posterior          NaN  ETA   0.0 min
  !! trait error 1 — java.lang.Error: randomChoiceUnnormalized falls through -- negative components i
  !! trait error 2 — Caused by: java.lang.Error: randomChoiceUnnormalized falls through -- negative c
  	at beastclassic.evolution.likelihood.AncestralStateTreeLikelihood.redrawAncestralStates(Unknown Sou
  	at beastclassic.evolution.likelihood.AncestralStateTreeLikelihood.getStatesForNode(Unknown Source)
  	at beastclassic.evolution.likelihood.AncestralStateTreeLikelihood$1.getTraitString(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)
  	at beastclassic.evolution.tree.TreeWithTraitLogger.toNewick(Unknown Source)

KeyboardInterrupt:

In [49]:
import shutil, subprocess, time, re
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

SRC         = Path("beast/clade3/clade3_dta_nobssvs.xml").resolve()
FINAL       = SRC.parent / "clade3_dta_final.xml"
SEEDS       = [12345, 54321]
THREADS     = 4
TIMEOUT_MIN = 120
REMAP       = {"ailurid": "wild_felid"}

# ---------- 1. merge the single-sequence state ----------
tree = ET.parse(SRC); root = tree.getroot()
changed = 0
for el in root.iter():
    tn = el.get("traitname")
    if not tn or tn.startswith("date"):
        continue
    src = "attr" if el.get("value") else "text"
    val = el.get("value") or (el.text or "")
    pairs = [y.strip() for y in val.replace("\n", " ").split(",") if "=" in y]
    if not pairs:
        continue
    print(f"<{el.tag}> traitname={tn!r} taxa={len(pairs)}")
    print("  before:", dict(Counter(y.rsplit('=',1)[1].strip() for y in pairs)))
    new = [f"{y.rsplit('=',1)[0].strip()}="
           f"{REMAP.get(y.rsplit('=',1)[1].strip(), y.rsplit('=',1)[1].strip())}" for y in pairs]
    print("  after :", dict(Counter(y.rsplit('=',1)[1] for y in new)))
    if src == "attr":
        el.set("value", ",".join(new))
    else:
        el.text = "\n" + ",\n".join(new) + "\n"
    changed += 1
if not changed:
    raise RuntimeError("no discrete traitset found")
tree.write(FINAL, encoding="unicode", xml_declaration=True)

# ---------- 2. verify ----------
raw = FINAL.read_text(); r = ET.fromstring(raw)
chain = re.search(r'chainLength="(\d+)"', raw)
total = int(chain.group(1)) if chain else None
print(f"\n{FINAL.name}")
print(f"  partitions : {len(r.findall('.//data'))}")
print(f"  chainLength: {total:,}" if total else "  chainLength: ?")
print(f"  BSSVS off  : {'indicator' not in raw.lower()}")
print(f"  ailurid    : {raw.count('=ailurid')} remaining")
print(f"  loggers    : {[x.get('fileName') for x in r.findall('.//logger') if x.get('fileName')]}")

# ---------- 3. park old outputs ----------
old = SRC.parent / "previous_runs"
for f in list(SRC.parent.glob("clade3_dta.*")) + list(SRC.parent.glob("Host_tree_with_trait*")):
    if f.is_file() and f.suffix in (".log", ".trees"):
        old.mkdir(exist_ok=True); shutil.move(str(f), old / f.name)

def find_beast():
    exe = shutil.which("beast")
    if exe: return exe
    for rt in [Path("/Applications"), Path.home()/"Applications", Path.home()]:
        if rt.is_dir():
            for pat in ("BEAST*/bin/beast", "*/BEAST*/bin/beast"):
                hits = sorted(rt.glob(pat))
                if hits: return str(hits[0])
    return None

beast = find_beast()
if not beast:
    raise RuntimeError("BEAST not found")

# ---------- 4. run both chains ----------
for seed in SEEDS:
    print("\n" + "="*66); print(f"  CHAIN seed={seed}"); print("="*66)
    t0 = time.time(); errors = 0; posteriors = []; tail = []; ok500 = False
    proc = subprocess.Popen([beast, "-seed", str(seed), "-threads", str(THREADS),
                             "-overwrite", str(FINAL)],
                            cwd=str(FINAL.parent), stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True, bufsize=1)
    try:
        for line in proc.stdout:
            line = line.rstrip(); tail.append(line); tail[:] = tail[-30:]
            if "randomchoiceunnormalized" in line.lower():
                errors += 1
                if errors <= 2: print(f"  !! trait error {errors}")
            parts = line.split()
            if len(parts) >= 2 and parts[0].isdigit():
                state = int(parts[0])
                if state > 500_000 and not ok500 and errors == 0:
                    ok500 = True; print("  >> 500k states clean")
                try:
                    posteriors.append(float(parts[1]))
                    if len(posteriors) % 50 == 1 and total:
                        el = time.time()-t0; frac = state/total
                        eta = (el/frac - el)/60 if frac > 0.01 else 0
                        print(f"  [{el/60:5.1f} min] {state:>12,}  {parts[1]:>12}  ETA {eta:5.1f} min")
                except ValueError:
                    pass
            if time.time()-t0 > TIMEOUT_MIN*60:
                proc.kill(); print("  KILLED on timeout"); break
    finally:
        proc.wait()

    print(f"  exit {proc.returncode} in {(time.time()-t0)/60:.1f} min | trait errors: {errors}")
    if proc.returncode != 0:
        print("  last lines:\n    " + "\n    ".join(tail[-8:])); break

    for f in ["clade3_dta.log", "clade3_dta.trees", "Host_tree_with_trait.trees"]:
        p = FINAL.parent / f
        if p.exists():
            p.rename(FINAL.parent / f.replace(".", f"_seed{seed}.", 1))

print("\nfinal outputs:")
for f in sorted(FINAL.parent.glob("*seed*")):
    print(f"  {f.name:<48} {f.stat().st_size/1024:>10.1f} KB")

<traitSet> traitname='discrete' taxa=162
  before: {'procyonid': 91, 'wild_felid': 7, 'wild_canid': 32, 'domestic_dog': 8, 'mustelid': 23, 'ailurid': 1}
  after : {'procyonid': 91, 'wild_felid': 8, 'wild_canid': 32, 'domestic_dog': 8, 'mustelid': 23}

clade3_dta_final.xml
  partitions : 2
  chainLength: 10,000,000
  BSSVS off  : False
  ailurid    : 0 remaining
  loggers    : ['clade3_dta.log', 'clade3_dta.trees', 'Host_tree_with_trait.trees']

==================================================================
  CHAIN seed=12345
==================================================================
  [  0.0 min]            0   -38953.1594  ETA   0.0 min
  [  0.3 min]       50,000   -11886.5946  ETA   0.0 min

KeyboardInterrupt:

In [50]:
from pathlib import Path
import re
raw = Path("beast/clade3/clade3_dta_nobssvs.xml").read_text()
for kw in ["indicator", "SVSGeneralSubstitutionModel", "GeneralSubstitutionModel",
           "Symmetric", "Asymmetric", "BSSVS", "nonZeroRates"]:
    print(f"  {kw:<32} {raw.lower().count(kw.lower())}")
print("\nlines mentioning indicator or SubstitutionModel:")
for l in raw.splitlines():
    if re.search(r"indicator|SubstitutionModel", l, re.I):
        print("   ", l.strip()[:120])

  indicator                        9
  SVSGeneralSubstitutionModel      2
  GeneralSubstitutionModel         2
  Symmetric                        0
  Asymmetric                       0
  BSSVS                            2
  nonZeroRates                     1

lines mentioning indicator or SubstitutionModel:
    <?xml version="1.0" encoding="UTF-8" standalone="no"?><beast beautitemplate='Standard' beautistatus='' namespace="beast.
    <stateNode id="rateIndicator.s:Host" spec="parameter.BooleanParameter" dimension="15">true</stateNode>
    <arg idref="rateIndicator.s:Host"/>
    <substModel id="svs.s:Host" spec="beastclassic.evolution.substitutionmodel.SVSGeneralSubstitutionModel" rateIndicator="@
    <operator id="indicatorFlip.s:Host" spec="operator.BitFlipOperator" parameter="@rateIndicator.s:Host" weight="30.0"/>
    <operator id="BSSVSoperator.c:Host" spec="beastclassic.evolution.operators.BitFlipBSSVSOperator" indicator="@rateIndicat
    <log idref="rateIndicator.s:Host"/>
    <log id="geoSubstModelLogger.s:Host" spec="beastclassic.evolution.substitutionmodel.SVSGeneralSubstitutionModelLogger" d

In [51]:
from pathlib import Path
from collections import Counter

src = Path("data/processed/H_clade_3.fasta")
out = Path("data/processed/H_clade_3_5state.fasta")

lines, hosts = [], []
for l in src.read_text().splitlines():
    if l.startswith(">"):
        acc, host, year = l[1:].split()[0].split("|")
        if host == "ailurid":
            host = "wild_felid"      # single observation folded in
        hosts.append(host)
        lines.append(f">{acc}|{host}|{year}")
    elif l.strip():
        lines.append(l.strip())
out.write_text("\n".join(lines) + "\n")

print(f"{len(hosts)} sequences -> {out.name}")
print(dict(Counter(hosts)))
print("states:", len(set(hosts)), "-> rateIndicator dimension should be",
      len(set(hosts))*(len(set(hosts))-1)//2, "if symmetric")

162 sequences -> H_clade_3_5state.fasta
{'procyonid': 91, 'wild_felid': 8, 'wild_canid': 32, 'domestic_dog': 8, 'mustelid': 23}
states: 5 -> rateIndicator dimension should be 10 if symmetric

In [52]:
from pathlib import Path
d = Path("data/processed")
print("in data/processed:")
for f in sorted(d.glob("*.fasta")):
    print(f"  {f.name:<40} {f.stat().st_size/1024:>8.1f} KB")

in data/processed:
  H_aligned.fasta                            3530.0 KB
  H_clade_3.fasta                             324.5 KB
  H_clade_3_5state.fasta                      324.5 KB
  H_clade_3_clean.fasta                       318.3 KB
  H_global400.fasta                           801.8 KB
  H_global400_clean.fasta                     801.4 KB
  H_labelled.fasta                           2558.5 KB
  sequences_H.fasta                          2526.5 KB
  sequences_all.fasta                        5527.1 KB

In [54]:
from pathlib import Path
import xml.etree.ElementTree as ET
from collections import Counter

p = Path("beast/clade3/clade3_5state.xml")
raw = p.read_text(); r = ET.fromstring(raw)

print("partitions   :", len(r.findall(".//data")))
print("chainLength  :", [x.get("chainLength") for x in r.findall(".//run")])
print("rateIndicator:", raw.count("rateIndicator"), "(want 0)")
import re
m = re.search(r'rateIndicator[^>]*dimension="(\d+)"', raw)
print("  dimension  :", m.group(1) if m else "none — BSSVS is off")
print("loggers      :", [x.get("fileName") for x in r.findall(".//logger") if x.get("fileName")])

for el in r.iter():
    tn = el.get("traitname")
    if tn and not tn.startswith("date"):
        val = el.get("value") or (el.text or "")
        pairs = [y.strip() for y in val.replace("\n"," ").split(",") if "=" in y]
        print("trait states :", dict(Counter(y.rsplit('=',1)[1] for y in pairs)))

partitions   : 2
chainLength  : ['10000000']
rateIndicator: 3 (want 0)
  dimension  : 10
loggers      : ['clade3_5state.log', 'clade3_5state.trees', 'clade3_5state.host.trees']
trait states : {'procyonid': 91, 'wild_felid': 8, 'wild_canid': 32, 'domestic_dog': 8, 'mustelid': 23}

In [55]:
from pathlib import Path
raw = Path("beast/clade3/clade3_5state.xml").read_text()
for kw in ["indicatorFlip", "BSSVSoperator", "BitFlip", "nonZeroRates"]:
    print(f"  {kw:<20} {raw.count(kw)}")
print("\nrateIndicator lines:")
for l in raw.splitlines():
    if "rateIndicator" in l:
        print("   ", l.strip()[:130])

  indicatorFlip        0
  BSSVSoperator        0
  BitFlip              0
  nonZeroRates         0

rateIndicator lines:
    <rateIndicator id="rateIndicator.s:host" spec="parameter.BooleanParameter" dimension="10" estimate="false">true</rateIndicator>

In [56]:
import shutil, subprocess, time, re
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

XML         = Path("beast/clade3/clade3_5state.xml").resolve()
SEEDS       = [12345, 54321]
THREADS     = 4
TIMEOUT_MIN = 150

# ---------- verify before committing ----------
raw = XML.read_text(); r = ET.fromstring(raw)
chain = re.search(r'chainLength="(\d+)"', raw)
total = int(chain.group(1)) if chain else None
states = {}
for el in r.iter():
    tn = el.get("traitname")
    if tn and not tn.startswith("date"):
        val = el.get("value") or (el.text or "")
        pairs = [y.strip() for y in val.replace("\n", " ").split(",") if "=" in y]
        if pairs:
            states = dict(Counter(y.rsplit('=', 1)[1] for y in pairs))

print(f"{XML.name}")
print(f"  partitions  : {len(r.findall('.//data'))}")
print(f"  chainLength : {total:,}" if total else "  chainLength : ?")
print(f"  trait states: {len(states)} -> {states}")
print(f"  BSSVS ops   : {sum(raw.count(k) for k in ('indicatorFlip','BSSVSoperator','BitFlip'))} (want 0)")
assert len(states) == 5, "expected 5 trait states"
assert sum(raw.count(k) for k in ("indicatorFlip", "BSSVSoperator", "BitFlip")) == 0, "BSSVS still active"

# ---------- park old outputs ----------
old = XML.parent / "previous_runs"
for f in XML.parent.glob("clade3_5state*"):
    if f.is_file() and f.suffix in (".log", ".trees"):
        old.mkdir(exist_ok=True); shutil.move(str(f), old / f.name)

def find_beast():
    exe = shutil.which("beast")
    if exe: return exe
    for rt in [Path("/Applications"), Path.home()/"Applications", Path.home()]:
        if rt.is_dir():
            for pat in ("BEAST*/bin/beast", "*/BEAST*/bin/beast"):
                hits = sorted(rt.glob(pat))
                if hits: return str(hits[0])
    return None

beast = find_beast()
if not beast:
    raise RuntimeError("BEAST not found")

# ---------- run both chains ----------
for seed in SEEDS:
    print("\n" + "="*66); print(f"  CHAIN seed={seed}"); print("="*66)
    t0, errors, posteriors, tail = time.time(), 0, [], []
    marks = {300_000: False, 1_500_000: False}
    proc = subprocess.Popen([beast, "-seed", str(seed), "-threads", str(THREADS),
                             "-overwrite", str(XML)],
                            cwd=str(XML.parent), stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True, bufsize=1)
    try:
        for line in proc.stdout:
            line = line.rstrip(); tail.append(line); tail[:] = tail[-30:]
            if "randomchoiceunnormalized" in line.lower():
                errors += 1
                if errors <= 2: print(f"  !! trait error {errors} — model still unstable")
            parts = line.split()
            if len(parts) >= 2 and parts[0].isdigit():
                state = int(parts[0])
                for mark in marks:
                    if state > mark and not marks[mark] and errors == 0:
                        marks[mark] = True
                        print(f"  >> past {mark:,} clean "
                              f"({'first crash point' if mark == 300_000 else 'second crash point'})")
                try:
                    posteriors.append(float(parts[1]))
                    if len(posteriors) % 50 == 1 and total:
                        el = time.time() - t0; frac = state/total
                        eta = (el/frac - el)/60 if frac > 0.01 else 0
                        print(f"  [{el/60:5.1f} min] {state:>12,}  {parts[1]:>12}  ETA {eta:5.1f} min")
                except ValueError:
                    pass
            if time.time() - t0 > TIMEOUT_MIN*60:
                proc.kill(); print("  KILLED on timeout"); break
    finally:
        proc.wait()

    print(f"  exit {proc.returncode} in {(time.time()-t0)/60:.1f} min | trait errors: {errors}")
    if proc.returncode != 0:
        print("  last lines:\n    " + "\n    ".join(tail[-8:])); break

    for f in ["clade3_5state.log", "clade3_5state.trees", "clade3_5state.host.trees"]:
        p = XML.parent / f
        if p.exists():
            p.rename(XML.parent / f.replace(".", f"_seed{seed}.", 1))

print("\nfinal outputs:")
for f in sorted(XML.parent.glob("*seed*")):
    print(f"  {f.name:<48} {f.stat().st_size/1024:>10.1f} KB")

clade3_5state.xml
  partitions  : 2
  chainLength : 10,000,000
  trait states: 5 -> {'procyonid': 91, 'wild_felid': 8, 'wild_canid': 32, 'domestic_dog': 8, 'mustelid': 23}
  BSSVS ops   : 0 (want 0)

==================================================================
  CHAIN seed=12345
==================================================================
  [  0.0 min]            0   -38486.5912  ETA   0.0 min
  [  0.3 min]       50,000   -11341.6762  ETA   0.0 min
  [  0.6 min]      100,000    -9987.6442  ETA   0.0 min
  [  0.8 min]      150,000    -9821.3342  ETA  55.0 min
  [  1.1 min]      200,000    -9657.3917  ETA  54.6 min
  [  1.4 min]      250,000    -9648.1907  ETA  54.1 min
  [  1.7 min]      300,000    -9701.4674  ETA  53.6 min
  >> past 300,000 clean (first crash point)
  [  1.9 min]      350,000    -9654.8408  ETA  53.0 min
  [  2.2 min]      400,000    -9742.6317  ETA  52.7 min
  [  2.5 min]      450,000    -9673.4265  ETA  52.2 min
  [  2.7 min]      500,000    -9627.6028  ETA  51.7 min
  [  3.0 min]      550,000    -9693.1902  ETA  51.2 min
  [  3.3 min]      600,000    -9672.9327  ETA  50.9 min
  [  3.5 min]      650,000    -9672.5242  ETA  50.8 min
  [  3.8 min]      700,000    -9640.1757  ETA  50.3 min
  [  4.0 min]      750,000    -9633.0335  ETA  49.9 min
  [  4.3 min]      800,000    -9700.0690  ETA  49.5 min
  [  4.6 min]      850,000    -9662.9033  ETA  49.3 min
  [  4.8 min]      900,000    -9661.7221  ETA  48.9 min
  [  5.1 min]      950,000    -9651.8472  ETA  48.6 min
  [  5.4 min]    1,000,000    -9721.9868  ETA  48.3 min
  [  5.6 min]    1,050,000    -9734.8093  ETA  47.9 min
  [  5.9 min]    1,100,000    -9714.2379  ETA  47.6 min
  [  6.1 min]    1,150,000    -9691.7327  ETA  47.3 min
  [  6.4 min]    1,200,000    -9691.4315  ETA  47.1 min
  [  6.7 min]    1,250,000    -9687.3379  ETA  46.7 min
  [  6.9 min]    1,300,000    -9665.7704  ETA  46.3 min
  [  7.2 min]    1,350,000    -9645.1187  ETA  46.0 min
  [  7.4 min]    1,400,000    -9642.5826  ETA  45.6 min
  [  7.7 min]    1,450,000    -9675.0000  ETA  45.3 min
  [  7.9 min]    1,500,000    -9688.0062  ETA  45.0 min
  >> past 1,500,000 clean (second crash point)
  [  8.2 min]    1,550,000    -9678.1579  ETA  44.6 min
  [  8.4 min]    1,600,000    -9656.0471  ETA  44.3 min
  [  8.7 min]    1,650,000    -9580.8708  ETA  44.0 min
  [  8.9 min]    1,700,000    -9586.2744  ETA  43.7 min
  [  9.2 min]    1,750,000    -9649.5659  ETA  43.4 min
  [  9.5 min]    1,800,000    -9617.1669  ETA  43.1 min
  [  9.7 min]    1,850,000    -9622.7098  ETA  42.8 min
  [ 10.0 min]    1,900,000    -9629.0055  ETA  42.4 min
  [ 10.2 min]    1,950,000    -9644.6391  ETA  42.2 min
  [ 10.5 min]    2,000,000    -9569.6532  ETA  41.8 min
  [ 10.7 min]    2,050,000    -9651.6427  ETA  41.5 min
  [ 11.0 min]    2,100,000    -9658.0872  ETA  41.2 min
  [ 11.2 min]    2,150,000    -9610.0301  ETA  40.9 min
  [ 11.5 min]    2,200,000    -9651.9856  ETA  40.7 min
  [ 11.7 min]    2,250,000    -9681.0127  ETA  40.4 min
  [ 12.0 min]    2,300,000    -9700.1064  ETA  40.1 min
  [ 12.2 min]    2,350,000    -9723.6224  ETA  39.8 min
  [ 12.5 min]    2,400,000    -9747.7529  ETA  39.5 min
  [ 12.7 min]    2,450,000    -9723.8133  ETA  39.3 min
  [ 13.0 min]    2,500,000    -9662.8710  ETA  39.0 min
  [ 13.3 min]    2,550,000    -9650.4253  ETA  38.7 min
  [ 13.5 min]    2,600,000    -9687.9335  ETA  38.5 min
  [ 13.8 min]    2,650,000    -9702.4103  ETA  38.2 min
  [ 14.0 min]    2,700,000    -9686.9528  ETA  37.9 min
  [ 14.3 min]    2,750,000    -9624.0029  ETA  37.7 min
  [ 14.5 min]    2,800,000    -9698.7392  ETA  37.4 min
  [ 14.8 min]    2,850,000    -9668.0146  ETA  37.1 min
  [ 15.1 min]    2,900,000    -9602.6535  ETA  37.0 min
  [ 15.4 min]    2,950,000    -9698.8130  ETA  36.7 min
  [ 15.6 min]    3,000,000    -9662.3171  ETA  36.4 min
  [ 15.9 min]    3,050,000    -9679.5318  ETA  36.2 min
  [ 16.1 min]    3,100,000    -9649.3644  ETA  35.9 min
  [ 16.4 min]    3,150,000    -9669.6714  ETA  35.6 min
  [ 16.6 min]    3,200,000    -9727.3875  ETA  35.4 min
  [ 16.9 min]    3,250,000    -9658.3620  ETA  35.1 min
  [ 17.2 min]    3,300,000    -9657.4362  ETA  34.8 min
  [ 17.4 min]    3,350,000    -9684.7814  ETA  34.6 min
  [ 17.7 min]    3,400,000    -9663.4545  ETA  34.3 min
  [ 17.9 min]    3,450,000    -9683.9909  ETA  34.0 min
  [ 18.2 min]    3,500,000    -9663.7139  ETA  33.8 min
  [ 18.4 min]    3,550,000    -9655.1048  ETA  33.5 min
  [ 18.7 min]    3,600,000    -9611.4379  ETA  33.2 min
  [ 19.0 min]    3,650,000    -9671.3363  ETA  33.0 min
  [ 19.2 min]    3,700,000    -9741.7814  ETA  32.7 min
  [ 19.5 min]    3,750,000    -9665.4776  ETA  32.5 min
  [ 19.8 min]    3,800,000    -9634.2292  ETA  32.2 min
  [ 20.0 min]    3,850,000    -9643.5918  ETA  32.0 min
  [ 20.3 min]    3,900,000    -9586.0678  ETA  31.7 min
  [ 20.5 min]    3,950,000    -9637.0200  ETA  31.5 min
  [ 20.8 min]    4,000,000    -9634.5903  ETA  31.2 min
  [ 21.1 min]    4,050,000    -9703.2797  ETA  31.0 min
  [ 21.4 min]    4,100,000    -9675.4835  ETA  30.7 min
  [ 21.6 min]    4,150,000    -9699.3951  ETA  30.5 min
  [ 21.9 min]    4,200,000    -9587.0663  ETA  30.2 min
  [ 22.2 min]    4,250,000    -9620.5214  ETA  30.0 min
  [ 22.4 min]    4,300,000    -9672.9692  ETA  29.7 min
  [ 22.7 min]    4,350,000    -9602.2466  ETA  29.4 min
  [ 22.9 min]    4,400,000    -9637.2764  ETA  29.2 min
  [ 23.2 min]    4,450,000    -9631.9100  ETA  28.9 min
  [ 23.4 min]    4,500,000    -9683.2107  ETA  28.6 min
  [ 23.7 min]    4,550,000    -9659.5056  ETA  28.4 min
  [ 23.9 min]    4,600,000    -9630.9434  ETA  28.1 min
  [ 24.2 min]    4,650,000    -9653.2742  ETA  27.8 min
  [ 24.4 min]    4,700,000    -9662.4333  ETA  27.6 min
  [ 24.7 min]    4,750,000    -9656.8125  ETA  27.3 min
  [ 24.9 min]    4,800,000    -9724.3867  ETA  27.0 min
  [ 25.2 min]    4,850,000    -9640.9897  ETA  26.8 min
  [ 25.5 min]    4,900,000    -9658.1433  ETA  26.5 min
  [ 25.7 min]    4,950,000    -9673.0167  ETA  26.2 min
  [ 26.0 min]    5,000,000    -9693.5318  ETA  26.0 min
  [ 26.2 min]    5,050,000    -9623.3317  ETA  25.7 min
  [ 26.5 min]    5,100,000    -9571.5910  ETA  25.5 min
  [ 26.8 min]    5,150,000    -9652.9637  ETA  25.2 min
  [ 27.0 min]    5,200,000    -9703.0691  ETA  24.9 min
  [ 27.3 min]    5,250,000    -9653.6090  ETA  24.7 min
  [ 27.5 min]    5,300,000    -9609.7582  ETA  24.4 min
  [ 27.8 min]    5,350,000    -9588.3547  ETA  24.2 min
  [ 28.1 min]    5,400,000    -9629.5422  ETA  23.9 min
  [ 28.3 min]    5,450,000    -9592.5968  ETA  23.6 min
  [ 28.6 min]    5,500,000    -9613.6209  ETA  23.4 min
  [ 28.8 min]    5,550,000    -9604.2836  ETA  23.1 min
  [ 29.1 min]    5,600,000    -9623.8991  ETA  22.9 min
  [ 29.4 min]    5,650,000    -9668.0269  ETA  22.6 min
  [ 29.6 min]    5,700,000    -9649.7470  ETA  22.4 min
  [ 29.9 min]    5,750,000    -9588.6427  ETA  22.1 min
  [ 30.1 min]    5,800,000    -9584.7152  ETA  21.8 min
  [ 30.4 min]    5,850,000    -9605.7339  ETA  21.6 min
  [ 30.7 min]    5,900,000    -9599.7404  ETA  21.3 min
  [ 30.9 min]    5,950,000    -9614.3309  ETA  21.0 min
  [ 31.2 min]    6,000,000    -9704.1025  ETA  20.8 min
  [ 31.4 min]    6,050,000    -9676.4940  ETA  20.5 min
  [ 31.7 min]    6,100,000    -9699.2463  ETA  20.3 min
  [ 31.9 min]    6,150,000    -9635.6450  ETA  20.0 min
  [ 32.2 min]    6,200,000    -9647.6535  ETA  19.7 min
  [ 32.5 min]    6,250,000    -9672.2819  ETA  19.5 min
  [ 32.7 min]    6,300,000    -9678.6949  ETA  19.2 min
  [ 33.0 min]    6,350,000    -9655.6416  ETA  19.0 min
  [ 33.2 min]    6,400,000    -9654.4856  ETA  18.7 min
  [ 33.5 min]    6,450,000    -9687.5119  ETA  18.4 min
  [ 33.7 min]    6,500,000    -9682.4572  ETA  18.2 min
  [ 34.0 min]    6,550,000    -9672.5169  ETA  17.9 min
  [ 34.3 min]    6,600,000    -9696.2774  ETA  17.6 min
  [ 34.5 min]    6,650,000    -9617.2136  ETA  17.4 min
  [ 34.8 min]    6,700,000    -9599.5222  ETA  17.1 min
  [ 35.0 min]    6,750,000    -9543.0628  ETA  16.9 min
  [ 35.3 min]    6,800,000    -9633.7940  ETA  16.6 min
  [ 35.5 min]    6,850,000    -9629.6765  ETA  16.3 min
  [ 35.8 min]    6,900,000    -9620.5335  ETA  16.1 min
  [ 36.0 min]    6,950,000    -9668.7113  ETA  15.8 min
  [ 36.3 min]    7,000,000    -9675.7438  ETA  15.5 min
  [ 36.5 min]    7,050,000    -9644.6929  ETA  15.3 min
  [ 36.8 min]    7,100,000    -9626.5880  ETA  15.0 min
  [ 37.1 min]    7,150,000    -9610.6197  ETA  14.8 min
  [ 37.3 min]    7,200,000    -9668.6378  ETA  14.5 min
  [ 37.6 min]    7,250,000    -9696.9199  ETA  14.2 min
  [ 37.8 min]    7,300,000    -9673.4098  ETA  14.0 min
  [ 38.1 min]    7,350,000    -9671.1477  ETA  13.7 min
  [ 38.3 min]    7,400,000    -9682.2207  ETA  13.5 min
  [ 38.6 min]    7,450,000    -9690.0631  ETA  13.2 min
  [ 38.8 min]    7,500,000    -9686.4705  ETA  12.9 min
  [ 39.1 min]    7,550,000    -9685.4695  ETA  12.7 min
  [ 39.4 min]    7,600,000    -9643.4578  ETA  12.4 min
  [ 39.6 min]    7,650,000    -9603.8733  ETA  12.2 min
  [ 39.9 min]    7,700,000    -9663.6544  ETA  11.9 min
  [ 40.2 min]    7,750,000    -9647.4327  ETA  11.7 min
  [ 40.4 min]    7,800,000    -9664.4605  ETA  11.4 min
  [ 40.7 min]    7,850,000    -9672.7622  ETA  11.1 min
  [ 41.0 min]    7,900,000    -9605.9391  ETA  10.9 min
  [ 41.2 min]    7,950,000    -9719.8083  ETA  10.6 min
  [ 41.5 min]    8,000,000    -9666.2099  ETA  10.4 min
  [ 41.7 min]    8,050,000    -9623.3297  ETA  10.1 min
  [ 42.0 min]    8,100,000    -9663.1798  ETA   9.9 min
  [ 42.3 min]    8,150,000    -9632.4805  ETA   9.6 min
  [ 42.5 min]    8,200,000    -9627.3644  ETA   9.3 min
  [ 42.8 min]    8,250,000    -9673.6388  ETA   9.1 min
  [ 43.0 min]    8,300,000    -9623.8727  ETA   8.8 min
  [ 43.3 min]    8,350,000    -9658.9914  ETA   8.5 min
  [ 43.5 min]    8,400,000    -9710.1178  ETA   8.3 min
  [ 43.8 min]    8,450,000    -9653.1158  ETA   8.0 min
  [ 44.0 min]    8,500,000    -9640.5347  ETA   7.8 min
  [ 44.3 min]    8,550,000    -9619.5909  ETA   7.5 min
  [ 44.5 min]    8,600,000    -9727.5812  ETA   7.2 min
  [ 44.7 min]    8,650,000    -9647.9853  ETA   7.0 min
  [ 45.0 min]    8,700,000    -9641.7677  ETA   6.7 min
  [ 45.2 min]    8,750,000    -9618.9741  ETA   6.5 min
  [ 45.5 min]    8,800,000    -9597.8779  ETA   6.2 min
  [ 45.7 min]    8,850,000    -9657.0982  ETA   5.9 min
  [ 46.0 min]    8,900,000    -9670.1216  ETA   5.7 min
  [ 46.2 min]    8,950,000    -9579.4325  ETA   5.4 min
  [ 46.5 min]    9,000,000    -9601.2469  ETA   5.2 min
  [ 46.7 min]    9,050,000    -9637.0347  ETA   4.9 min
  [ 47.0 min]    9,100,000    -9666.7728  ETA   4.6 min
  [ 47.2 min]    9,150,000    -9675.9642  ETA   4.4 min
  [ 47.5 min]    9,200,000    -9721.9441  ETA   4.1 min
  [ 47.7 min]    9,250,000    -9683.7984  ETA   3.9 min
  [ 48.0 min]    9,300,000    -9642.4548  ETA   3.6 min
  [ 48.2 min]    9,350,000    -9669.9156  ETA   3.4 min
  [ 48.5 min]    9,400,000    -9643.7772  ETA   3.1 min
  [ 48.7 min]    9,450,000    -9680.4134  ETA   2.8 min
  [ 49.0 min]    9,500,000    -9629.9978  ETA   2.6 min
  [ 49.2 min]    9,550,000    -9637.8740  ETA   2.3 min
  [ 49.4 min]    9,600,000    -9664.2475  ETA   2.1 min
  [ 49.7 min]    9,650,000    -9667.2050  ETA   1.8 min
  [ 49.9 min]    9,700,000    -9728.2518  ETA   1.5 min
  [ 50.2 min]    9,750,000    -9762.0142  ETA   1.3 min
  [ 50.4 min]    9,800,000    -9657.6784  ETA   1.0 min
  [ 50.7 min]    9,850,000    -9622.2837  ETA   0.8 min
  [ 50.9 min]    9,900,000    -9634.1235  ETA   0.5 min
  [ 51.2 min]    9,950,000    -9642.2731  ETA   0.3 min
  [ 51.4 min]   10,000,000    -9667.3761  ETA   0.0 min
  exit 0 in 51.4 min | trait errors: 0

==================================================================
  CHAIN seed=54321
==================================================================
  [  0.0 min]            0   -36558.6518  ETA   0.0 min
  [  0.3 min]       50,000   -11184.5598  ETA   0.0 min
  [  0.6 min]      100,000   -10299.0946  ETA   0.0 min
  [  0.8 min]      150,000    -9902.7321  ETA  53.6 min
  [  1.1 min]      200,000    -9848.9696  ETA  52.5 min
  [  1.3 min]      250,000    -9672.1407  ETA  51.9 min
  [  1.6 min]      300,000    -9654.2605  ETA  51.2 min
  >> past 300,000 clean (first crash point)
  [  1.8 min]      350,000    -9658.3110  ETA  50.9 min
  [  2.1 min]      400,000    -9636.3808  ETA  50.5 min
  [  2.4 min]      450,000    -9597.4516  ETA  50.1 min
  [  2.6 min]      500,000    -9565.0083  ETA  49.5 min
  [  2.9 min]      550,000    -9527.7015  ETA  49.2 min
  [  3.1 min]      600,000    -9597.5045  ETA  48.7 min
  [  3.4 min]      650,000    -9571.6828  ETA  48.4 min
  [  3.6 min]      700,000    -9582.4647  ETA  48.0 min
  [  3.9 min]      750,000    -9624.4126  ETA  47.7 min
  [  4.1 min]      800,000    -9686.2750  ETA  47.4 min
  [  4.4 min]      850,000    -9689.0736  ETA  47.1 min
  [  4.6 min]      900,000    -9651.6289  ETA  46.8 min
  [  4.9 min]      950,000    -9733.5490  ETA  46.6 min
  [  5.2 min]    1,000,000    -9675.9417  ETA  46.4 min
  [  5.4 min]    1,050,000    -9619.2296  ETA  46.1 min
  [  5.7 min]    1,100,000    -9659.5943  ETA  45.9 min
  [  5.9 min]    1,150,000    -9647.9277  ETA  45.7 min
  [  6.2 min]    1,200,000    -9644.6826  ETA  45.4 min
  [  6.4 min]    1,250,000    -9599.5994  ETA  45.1 min
  [  6.7 min]    1,300,000    -9584.0079  ETA  44.8 min
  [  7.0 min]    1,350,000    -9653.5981  ETA  44.5 min
  [  7.2 min]    1,400,000    -9667.3657  ETA  44.3 min
  [  7.5 min]    1,450,000    -9682.3130  ETA  44.0 min
  [  7.7 min]    1,500,000    -9673.1091  ETA  43.8 min
  >> past 1,500,000 clean (second crash point)
  [  8.0 min]    1,550,000    -9642.1794  ETA  43.5 min
  [  8.2 min]    1,600,000    -9673.1249  ETA  43.2 min
  [  8.5 min]    1,650,000    -9601.8169  ETA  42.9 min
  [  8.7 min]    1,700,000    -9670.1449  ETA  42.7 min
  [  9.0 min]    1,750,000    -9671.5008  ETA  42.4 min
  [  9.2 min]    1,800,000    -9676.6805  ETA  42.1 min
  [  9.5 min]    1,850,000    -9672.5903  ETA  41.9 min
  [  9.8 min]    1,900,000    -9663.3314  ETA  41.6 min
  [ 10.0 min]    1,950,000    -9612.1847  ETA  41.4 min
  [ 10.3 min]    2,000,000    -9681.0318  ETA  41.1 min
  [ 10.5 min]    2,050,000    -9662.4074  ETA  40.9 min
  [ 10.8 min]    2,100,000    -9648.5590  ETA  40.7 min
  [ 11.1 min]    2,150,000    -9644.8629  ETA  40.4 min
  [ 11.3 min]    2,200,000    -9787.7095  ETA  40.2 min
  [ 11.6 min]    2,250,000    -9730.8715  ETA  39.9 min
  [ 11.8 min]    2,300,000    -9658.3944  ETA  39.6 min
  [ 12.1 min]    2,350,000    -9661.2228  ETA  39.4 min
  [ 12.4 min]    2,400,000    -9649.0938  ETA  39.2 min
  [ 12.6 min]    2,450,000    -9664.1580  ETA  38.9 min
  [ 12.9 min]    2,500,000    -9714.8852  ETA  38.7 min
  [ 13.1 min]    2,550,000    -9653.7916  ETA  38.4 min
  [ 13.4 min]    2,600,000    -9708.0754  ETA  38.1 min
  [ 13.6 min]    2,650,000    -9670.4174  ETA  37.8 min
  [ 13.9 min]    2,700,000    -9685.1376  ETA  37.6 min
  [ 14.1 min]    2,750,000    -9663.0918  ETA  37.3 min
  [ 14.4 min]    2,800,000    -9698.7479  ETA  37.0 min
  [ 14.6 min]    2,850,000    -9643.4156  ETA  36.7 min
  [ 14.9 min]    2,900,000    -9657.5949  ETA  36.5 min
  [ 15.1 min]    2,950,000    -9641.2239  ETA  36.2 min
  [ 15.4 min]    3,000,000    -9597.3336  ETA  35.9 min
  [ 15.6 min]    3,050,000    -9610.9883  ETA  35.6 min
  [ 15.9 min]    3,100,000    -9641.7208  ETA  35.3 min
  [ 16.1 min]    3,150,000    -9640.7942  ETA  35.1 min
  [ 16.4 min]    3,200,000    -9615.9485  ETA  34.8 min
  [ 16.6 min]    3,250,000    -9694.1713  ETA  34.6 min
  [ 16.9 min]    3,300,000    -9656.5205  ETA  34.3 min
  [ 17.1 min]    3,350,000    -9615.1560  ETA  34.0 min
  [ 17.4 min]    3,400,000    -9662.3038  ETA  33.8 min
  [ 17.6 min]    3,450,000    -9655.5793  ETA  33.5 min
  [ 17.9 min]    3,500,000    -9625.6871  ETA  33.2 min
  [ 18.1 min]    3,550,000    -9608.2669  ETA  33.0 min
  [ 18.4 min]    3,600,000    -9700.8917  ETA  32.7 min
  [ 18.6 min]    3,650,000    -9627.1954  ETA  32.4 min
  [ 18.9 min]    3,700,000    -9602.8210  ETA  32.1 min
  [ 19.1 min]    3,750,000    -9651.0847  ETA  31.9 min
  [ 19.4 min]    3,800,000    -9648.9771  ETA  31.6 min
  [ 19.6 min]    3,850,000    -9643.0181  ETA  31.4 min
  [ 19.9 min]    3,900,000    -9686.1426  ETA  31.1 min
  [ 20.1 min]    3,950,000    -9697.1927  ETA  30.8 min
  [ 20.4 min]    4,000,000    -9669.6219  ETA  30.6 min
  [ 20.6 min]    4,050,000    -9684.8549  ETA  30.3 min
  [ 20.9 min]    4,100,000    -9752.0910  ETA  30.1 min
  [ 21.1 min]    4,150,000    -9624.6720  ETA  29.8 min
  [ 21.4 min]    4,200,000    -9675.6963  ETA  29.5 min
  [ 21.7 min]    4,250,000    -9679.0264  ETA  29.3 min
  [ 21.9 min]    4,300,000    -9699.6066  ETA  29.0 min
  [ 22.2 min]    4,350,000    -9671.7423  ETA  28.8 min
  [ 22.4 min]    4,400,000    -9666.9331  ETA  28.5 min
  [ 22.7 min]    4,450,000    -9682.5899  ETA  28.3 min
  [ 23.0 min]    4,500,000    -9696.7366  ETA  28.1 min
  [ 23.2 min]    4,550,000    -9639.5841  ETA  27.8 min
  [ 23.5 min]    4,600,000    -9682.3207  ETA  27.6 min
  [ 23.7 min]    4,650,000    -9680.2412  ETA  27.3 min
  [ 24.0 min]    4,700,000    -9649.3377  ETA  27.0 min
  [ 24.2 min]    4,750,000    -9673.9455  ETA  26.8 min
  [ 24.5 min]    4,800,000    -9616.0839  ETA  26.5 min
  [ 24.7 min]    4,850,000    -9674.7016  ETA  26.3 min
  [ 25.0 min]    4,900,000    -9653.8482  ETA  26.0 min
  [ 25.3 min]    4,950,000    -9609.5311  ETA  25.8 min
  [ 25.5 min]    5,000,000    -9550.6654  ETA  25.5 min
  [ 25.7 min]    5,050,000    -9607.2384  ETA  25.2 min
  [ 26.0 min]    5,100,000    -9611.1917  ETA  25.0 min
  [ 26.2 min]    5,150,000    -9611.4998  ETA  24.7 min
  [ 26.5 min]    5,200,000    -9639.1022  ETA  24.5 min
  [ 26.7 min]    5,250,000    -9620.2347  ETA  24.2 min
  [ 27.0 min]    5,300,000    -9637.3928  ETA  23.9 min
  [ 27.2 min]    5,350,000    -9651.2877  ETA  23.7 min
  [ 27.5 min]    5,400,000    -9666.3654  ETA  23.4 min
  [ 27.7 min]    5,450,000    -9665.0291  ETA  23.2 min
  [ 28.0 min]    5,500,000    -9697.8835  ETA  22.9 min
  [ 28.2 min]    5,550,000    -9631.8353  ETA  22.6 min
  [ 28.5 min]    5,600,000    -9607.8154  ETA  22.4 min
  [ 28.7 min]    5,650,000    -9614.0149  ETA  22.1 min
  [ 29.0 min]    5,700,000    -9589.6984  ETA  21.9 min
  [ 29.2 min]    5,750,000    -9647.9498  ETA  21.6 min
  [ 29.5 min]    5,800,000    -9613.5262  ETA  21.3 min
  [ 29.7 min]    5,850,000    -9640.7543  ETA  21.1 min
  [ 30.0 min]    5,900,000    -9601.3499  ETA  20.8 min
  [ 30.2 min]    5,950,000    -9599.5249  ETA  20.6 min
  [ 30.5 min]    6,000,000    -9625.0387  ETA  20.3 min
  [ 30.7 min]    6,050,000    -9641.8725  ETA  20.1 min
  [ 31.0 min]    6,100,000    -9623.2510  ETA  19.8 min
  [ 31.2 min]    6,150,000    -9608.6972  ETA  19.6 min
  [ 31.5 min]    6,200,000    -9616.5821  ETA  19.3 min
  [ 31.7 min]    6,250,000    -9603.1750  ETA  19.0 min
  [ 32.0 min]    6,300,000    -9627.8623  ETA  18.8 min
  [ 32.3 min]    6,350,000    -9653.8256  ETA  18.5 min
  [ 32.5 min]    6,400,000    -9626.1479  ETA  18.3 min
  [ 32.8 min]    6,450,000    -9625.4787  ETA  18.0 min
  [ 33.1 min]    6,500,000    -9660.0931  ETA  17.8 min
  [ 33.3 min]    6,550,000    -9639.1336  ETA  17.5 min
  [ 33.6 min]    6,600,000    -9596.6126  ETA  17.3 min
  [ 33.8 min]    6,650,000    -9620.4151  ETA  17.0 min
  [ 34.1 min]    6,700,000    -9634.9210  ETA  16.8 min
  [ 34.4 min]    6,750,000    -9658.6906  ETA  16.6 min
  [ 34.6 min]    6,800,000    -9627.0346  ETA  16.3 min
  [ 34.9 min]    6,850,000    -9608.7282  ETA  16.1 min
  [ 35.2 min]    6,900,000    -9666.2405  ETA  15.8 min
  [ 35.5 min]    6,950,000    -9647.5521  ETA  15.6 min
  [ 35.7 min]    7,000,000    -9702.8260  ETA  15.3 min
  [ 36.0 min]    7,050,000    -9645.8122  ETA  15.1 min
  [ 36.3 min]    7,100,000    -9644.0880  ETA  14.8 min

In [58]:
from pathlib import Path
d = Path("beast/clade3")
for f in sorted(d.glob("*seed12345*")):
    print(f"  {f.name:<48} {f.stat().st_size/1024:>10.1f} KB")

  clade3_5state_seed12345.host.trees                  14177.6 KB
  clade3_5state_seed12345.log                           783.9 KB
  clade3_5state_seed12345.trees                       15729.4 KB

In [59]:
from pathlib import Path
import xml.etree.ElementTree as ET
import re

XML = Path("beast/clade3/clade3_5state.xml")
raw = XML.read_text()

print(f"{XML.name}\n")
print(f"UpDown occurrences : {raw.lower().count('updown')}")

# list every operator so we can see what's actually moving the tree and clock
print("\noperators:")
root = ET.fromstring(raw)
for op in root.findall(".//operator"):
    spec = op.get("spec", "")
    oid  = op.get("id", "")
    wt   = op.get("weight", "")
    targets = [op.get(k) for k in ("parameter", "tree", "up", "down") if op.get(k)]
    print(f"  {oid:<44} {spec:<28} w={wt:<6} {' '.join(targets)}")

# which operators touch the clock rate and tree height?
print("\noperators touching ucldMean:")
for op in

SyntaxError: invalid syntax (796188375.py, line 23)

In [60]:
from pathlib import Path
import xml.etree.ElementTree as ET
import re

XML = Path("beast/clade3/clade3_5state.xml")
raw = XML.read_text()

print(f"{XML.name}\n")
print(f"UpDown occurrences : {raw.lower().count('updown')}")

# list every operator so we can see what's actually moving the tree and clock
print("\noperators:")
root = ET.fromstring(raw)
for op in root.findall(".//operator"):
    spec = op.get("spec", "")
    oid  = op.get("id", "")
    wt   = op.get("weight", "")
    targets = [op.get(k) for k in ("parameter", "tree", "up", "down") if op.get(k)]
    print(f"  {oid:<44} {spec:<28} w={wt:<6} {' '.join(targets)}")

# which operators touch the clock rate and tree height?
print("\noperators touching ucldMean:")
for op in root.findall(".//operator"):
    if "ucldMean" in ET.tostring(op, encoding="unicode"):
        print(f"  {op.get('id')}  ({op.get('spec')}, weight {op.get('weight')})")

print("\noperators touching the tree:")
for op in root.findall(".//operator"):
    if op.get("tree") or "Tree.t" in ET.tostring(op, encoding="unicode"):
        print(f"  {op.get('id')}  ({op.get('spec')}, weight {op.get('weight')})")

clade3_5state.xml

UpDown occurrences : 2

operators:
  geoMuScaler.c:host                           ScaleOperator                w=3.0    @traitClockRate.c:host
  georateScaler.s:host                         ScaleOperator                w=30.0   @relativeGeoRates.s:host
  KappaScaler.s:H_clade_3_5state               AdaptableOperatorSampler     w=0.05
  AVMNOperator.H_clade_3_5state                kernel.AdaptableVarianceMultivariateNormalOperator w=0.1
  KappaScalerX.s:H_clade_3_5state              kernel.BactrianScaleOperator w=0.1    @kappa.s:H_clade_3_5state
  FrequenciesExchanger.s:H_clade_3_5state      AdaptableOperatorSampler     w=0.05
                                                                            w=
  FrequenciesExchangerX.s:H_clade_3_5state     operator.kernel.BactrianDeltaExchangeOperator w=0.1
  gammaShapeScaler.s:H_clade_3_5state          AdaptableOperatorSampler     w=0.05
                                                                            w=
  gammaShapeScalerX.s:H_clade_3_5state         kernel.BactrianScaleOperator w=0.1    @gammaShape.s:H_clade_3_5state
  CoalescentConstantBICEPSEpochTop.t:H_clade_3_5state EpochFlexOperator            w=2.0    @Tree.t:H_clade_3_5state
  CoalescentConstantBICEPSEpochAll.t:H_clade_3_5state EpochFlexOperator            w=2.0    @Tree.t:H_clade_3_5state
  CoalescentConstantBICEPSTreeFlex.t:H_clade_3_5state TreeStretchOperator          w=2.0    @Tree.t:H_clade_3_5state
  CoalescentConstantTreeRootScaler.t:H_clade_3_5state kernel.BactrianScaleOperator w=3.0    @Tree.t:H_clade_3_5state
  CoalescentConstantUniformOperator.t:H_clade_3_5state kernel.BactrianNodeOperator  w=30.0   @Tree.t:H_clade_3_5state
  CoalescentConstantSubtreeSlide.t:H_clade_3_5state kernel.BactrianSubtreeSlide  w=15.0   @Tree.t:H_clade_3_5state
  CoalescentConstantNarrow.t:H_clade_3_5state  Exchange                     w=15.0   @Tree.t:H_clade_3_5state
  CoalescentConstantWide.t:H_clade_3_5state    Exchange                     w=3.0    @Tree.t:H_clade_3_5state
  CoalescentConstantWilsonBalding.t:H_clade_3_5state WilsonBalding                w=3.0    @Tree.t:H_clade_3_5state
  PopSizeScaler.t:H_clade_3_5state             kernel.BactrianScaleOperator w=3.0    @popSize.t:H_clade_3_5state
  ucldMeanScaler.c:H_clade_3_5state            ScaleOperator                w=1.0    @ucldMean.c:H_clade_3_5state
  ucldStdevScaler.c:H_clade_3_5state           ScaleOperator                w=3.0    @ucldStdev.c:H_clade_3_5state
  CategoriesRandomWalk.c:H_clade_3_5state      operator.IntRandomWalkOperator w=10.0   @rateCategories.c:H_clade_3_5state
  CategoriesSwapOperator.c:H_clade_3_5state    operator.SwapOperator        w=10.0
  CategoriesUniform.c:H_clade_3_5state         operator.UniformOperator     w=10.0   @rateCategories.c:H_clade_3_5state
  relaxedUpDownOperator.c:H_clade_3_5state     operator.UpDownOperator      w=3.0

operators touching ucldMean:
  ucldMeanScaler.c:H_clade_3_5state  (ScaleOperator, weight 1.0)
  relaxedUpDownOperator.c:H_clade_3_5state  (operator.UpDownOperator, weight 3.0)

operators touching the tree:
  KappaScaler.s:H_clade_3_5state  (AdaptableOperatorSampler, weight 0.05)
  AVMNOperator.H_clade_3_5state  (kernel.AdaptableVarianceMultivariateNormalOperator, weight 0.1)
  CoalescentConstantBICEPSEpochTop.t:H_clade_3_5state  (EpochFlexOperator, weight 2.0)
  CoalescentConstantBICEPSEpochAll.t:H_clade_3_5state  (EpochFlexOperator, weight 2.0)
  CoalescentConstantBICEPSTreeFlex.t:H_clade_3_5state  (TreeStretchOperator, weight 2.0)
  CoalescentConstantTreeRootScaler.t:H_clade_3_5state  (kernel.BactrianScaleOperator, weight 3.0)
  CoalescentConstantUniformOperator.t:H_clade_3_5state  (kernel.BactrianNodeOperator, weight 30.0)
  CoalescentConstantSubtreeSlide.t:H_clade_3_5state  (kernel.BactrianSubtreeSlide, weight 15.0)
  CoalescentConstantNarrow.t:H_clade_3_5state  (Exchange, weight 15.0)
  CoalescentConstantWide.t:H_clade_3_5state  (Exchange, weight 3.0)
  CoalescentConstantWilsonBalding.t:H_clade_3_5state  (WilsonBalding, weight 3.0)
  relaxedUpDownOperator.c:H_clade_3_5state  (operator.UpDownOperator, weight 3.0)

In [1]:
import re, shutil, subprocess, os, stat, shlex
from pathlib import Path

SRC       = Path("beast/clade3/clade3_5state.xml").resolve()
CHAIN     = 100_000_000
LOG_EVERY = 100_000          # keeps 1000 samples per file at 100M
SEEDS     = [12345, 54321]
THREADS   = 4
RUNDIR    = SRC.parent / "run100M"

def find_beast():
    exe = shutil.which("beast")
    if exe: return exe
    for rt in [Path("/Applications"), Path.home()/"Applications", Path.home()]:
        if rt.is_dir():
            for pat in ("BEAST*/bin/beast", "*/BEAST*/bin/beast"):
                hits = sorted(rt.glob(pat))
                if hits: return str(hits[0])
    raise RuntimeError("BEAST not found")

beast = find_beast()

raw = SRC.read_text()
raw, n1 = re.subn(r'(chainLength=")\d+(")', rf'\g<1>{CHAIN}\g<2>', raw)
def fix(m):
    return m.group(0) if 'id="screenlog"' in m.group(0) else re.sub(
        r'logEvery="\d+"', f'logEvery="{LOG_EVERY}"', m.group(0))
raw, n2 = re.subn(r'<logger\b[^>]*>', fix, raw)
print(f"chainLength -> {CHAIN:,} ({n1} edit), logEvery -> {LOG_EVERY:,} ({n2} loggers)")

# each chain gets its own directory, so the fixed output filenames don't collide
for seed in SEEDS:
    sd = RUNDIR / f"seed{seed}"
    sd.mkdir(parents=True, exist_ok=True)
    (sd / SRC.name).write_text(raw)

lines = ["#!/bin/bash", "set -e"]
for seed in SEEDS:
    sd = RUNDIR / f"seed{seed}"
    lines += [f'echo "=== seed {seed} started $(date) ==="',
              f'cd {shlex.quote(str(sd))}',
              f'{shlex.quote(beast)} -seed {seed} -threads {THREADS} -overwrite '
              f'{shlex.quote(str(sd / SRC.name))} > run.out 2>&1',
              f'echo "=== seed {seed} finished $(date) ==="']
sh = RUNDIR / "run_all.sh"
sh.write_text("\n".join(lines) + "\n")
sh.chmod(sh.stat().st_mode | stat.S_IEXEC)

# caffeinate stops the Mac sleeping; nohup detaches from the kernel
proc = subprocess.Popen(
    f"nohup caffeinate -i {shlex.quote(str(sh))} > {shlex.quote(str(RUNDIR/'driver.log'))} 2>&1 &",
    shell=True, cwd=str(RUNDIR))

print(f"\nlaunched, pid group detached")
print(f"driver log : {RUNDIR/'driver.log'}")
print(f"chain logs : {RUNDIR}/seed*/run.out")
print(f"\nEstimated ~9 h per chain, ~18 h total. Safe to close this notebook.")
print("Leave the laptop plugged in. Closing the lid still sleeps it — use")
print("System Settings > Lock Screen, or just leave it open.")

FileNotFoundError: [Errno 2] No such file or directory: '/Users/batyanightingale/projects/cdv-phylodynamics/notebooks/beast/clade3/clade3_5state.xml'

In [2]:
import os
from pathlib import Path
ROOT = Path.cwd()
while not (ROOT / "scripts").is_dir() and ROOT != ROOT.parent:
    ROOT = ROOT.parent
os.chdir(ROOT)
print("cwd:", Path.cwd())

cwd: /Users/batyanightingale/projects/cdv-phylodynamics

In [3]:
import os, re, shutil, subprocess, stat, shlex, sys
from pathlib import Path

# ---------- 1. get to the repo root ----------
ROOT = Path.cwd()
while not (ROOT / "scripts").is_dir() and ROOT != ROOT.parent:
    ROOT = ROOT.parent
if not (ROOT / "scripts").is_dir():
    raise RuntimeError(f"repo root not found from {Path.cwd()} — set it manually")
os.chdir(ROOT)
print(f"repo root : {ROOT}")

# ---------- 2. environment report ----------
print(f"python    : {sys.executable}")
in_env = "cdv-phylo" in sys.executable
print(f"kernel env: {'cdv-phylo' if in_env else 'NOT cdv-phylo (base?)'}")
if not in_env:
    print("  ^ fine for launching BEAST (it is a separate Java app).")
    print("    Switch kernels tomorrow before any pipeline work.")

# ---------- 3. find BEAST ----------
def find_beast():
    exe = shutil.which("beast")
    if exe: return exe
    for rt in [Path("/Applications"), Path.home()/"Applications", Path.home()]:
        if rt.is_dir():
            for pat in ("BEAST*/bin/beast", "*/BEAST*/bin/beast"):
                hits = sorted(rt.glob(pat))
                if hits: return str(hits[0])
    raise RuntimeError("BEAST not found — set `beast` manually")

beast = find_beast()
print(f"beast     : {beast}")

# ---------- 4. build the 100M XMLs ----------
SRC       = (ROOT / "beast/clade3/clade3_5state.xml").resolve()
CHAIN     = 100_000_000
LOG_EVERY = 100_000
SEEDS     = [12345, 54321]
THREADS   = 4
RUNDIR    = SRC.parent / "run100M"

if not SRC.is_file():
    raise FileNotFoundError(f"{SRC} missing. In {SRC.parent}: "
        f"{sorted(p.name for p in SRC.parent.iterdir()) if SRC.parent.is_dir() else 'dir missing'}")

raw = SRC.read_text()
raw, n_chain = re.subn(r'(chainLength=")\d+(")', rf'\g<1>{CHAIN}\g<2>', raw)
def fix(m):
    return m.group(0) if 'id="screenlog"' in m.group(0) else re.sub(
        r'logEvery="\d+"', f'logEvery="{LOG_EVERY}"', m.group(0))
raw, n_log = re.subn(r'<logger\b[^>]*>', fix, raw)

print(f"\nchainLength -> {CHAIN:,}   ({n_chain} edit, want 1)")
print(f"logEvery    -> {LOG_EVERY:,}   ({n_log} loggers scanned, want 4)")
assert n_chain == 1, "chainLength not edited — check the XML"

for seed in SEEDS:
    sd = RUNDIR / f"seed{seed}"
    sd.mkdir(parents=True, exist_ok=True)
    (sd / SRC.name).write_text(raw)
print(f"run dirs   : {[p.name for p in sorted(RUNDIR.glob('seed*'))]}")

# ---------- 5. driver script ----------
lines = ["#!/bin/bash", "set -e"]
for seed in SEEDS:
    sd = RUNDIR / f"seed{seed}"
    lines += [f'echo "=== seed {seed} started $(date) ==="',
              f'cd {shlex.quote(str(sd))}',
              f'{shlex.quote(beast)} -seed {seed} -threads {THREADS} -overwrite '
              f'{shlex.quote(str(sd / SRC.name))} > run.out 2>&1',
              f'echo "=== seed {seed} finished $(date) ==="']
sh = RUNDIR / "run_all.sh"
sh.write_text("\n".join(lines) + "\n")
sh.chmod(sh.stat().st_mode | stat.S_IEXEC)

# ---------- 6. launch, detached ----------
subprocess.Popen(
    f"nohup caffeinate -i {shlex.quote(str(sh))} > {shlex.quote(str(RUNDIR/'driver.log'))} 2>&1 &",
    shell=True, cwd=str(RUNDIR))

print(f"\nLAUNCHED — detached from this notebook")
print(f"  driver log : {RUNDIR/'driver.log'}")
print(f"  chain output: {RUNDIR}/seed*/run.out")
print(f"\n~9 h per chain, ~18 h total. Safe to close Jupyter.")
print("Keep it plugged in and leave the lid open — caffeinate stops idle sleep,")
print("not lid-close sleep.")

repo root : /Users/batyanightingale/projects/cdv-phylodynamics
python    : /Users/batyanightingale/anaconda3/bin/python
kernel env: NOT cdv-phylo (base?)
  ^ fine for launching BEAST (it is a separate Java app).
    Switch kernels tomorrow before any pipeline work.
beast     : /Applications/BEAST 2.7.7/bin/beast

chainLength -> 100,000,000   (1 edit, want 1)
logEvery    -> 100,000   (4 loggers scanned, want 4)
run dirs   : ['seed12345', 'seed54321']

LAUNCHED — detached from this notebook
  driver log : /Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/run100M/driver.log
  chain output: /Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/run100M/seed*/run.out

~9 h per chain, ~18 h total. Safe to close Jupyter.
Keep it plugged in and leave the lid open — caffeinate stops idle sleep,
not lid-close sleep.

In [4]:
from pathlib import Path
import time

RUNDIR = Path("/Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/run100M")
TOTAL = 100_000_000

drv = RUNDIR / "driver.log"
print(drv.read_text() if drv.exists() else "no driver log yet")
for sd in sorted(RUNDIR.glob("seed*")):
    log, out = sd / "clade3_5state.log", sd / "run.out"
    print(f"\n{sd.name}")
    if not out.exists():
        print("  not started yet"); continue
    if log.exists():
        rows = [l for l in log.read_text().splitlines()
                if l and not l.startswith("#") and l.split()[0].isdigit()]
        if rows:
            state = int(rows[-1].split()[0])
            print(f"  state {state:,} / {TOTAL:,}  ({state/TOTAL:.1%})")
            print(f"  last write {(time.time()-out.stat().st_mtime)/60:.0f} min ago")
        else:
            print("  log exists, no samples yet (normal in the first few minutes)")
    tail = out.read_text().splitlines()[-3:]
    print("  " + "\n  ".join(t[:90] for t in tail))

=== seed 12345 started Thu Aug 27 23:53:39 EDT 2026 ===


seed12345
  state 100,000 / 100,000,000  (0.1%)
  last write 0 min ago
           128000    -10202.7289     -9304.3429      -898.3859 5m52s/Msamples
           129000    -10215.2547     -9309.2004      -906.0543 5m52s/Msamples
           130000    -10216.3828     -9295.9225      -920.4603 5m52s/Msamples

seed54321
  not started yet

In [5]:
from pathlib import Path
import statistics, time

RUNDIR = Path("/Users/batyanightingale/projects/cdv-phylodynamics/beast/clade3/run100M")
TOTAL  = 100_000_000

def ess_rough(x):
    """Approximate ESS via autocorrelation. Indicative only — use Tracer for the real number."""
    n = len(x)
    if n < 10: return 0
    m, v = statistics.mean(x), statistics.pvariance(x)
    if v == 0: return 0
    s = 0.0
    for lag in range(1, min(n//3, 500)):
        c = sum((x[i]-m)*(x[i+lag]-m) for i in range(n-lag))/(n-lag)/v
        if c < 0.05: break
        s += c
    return n/(1+2*s)

drv = RUNDIR / "driver.log"
print(drv.read_text() if drv.exists() else "no driver log\n")

for sd in sorted(RUNDIR.glob("seed*")):
    print(f"--- {sd.name} ---")
    log, out = sd / "clade3_5state.log", sd / "run.out"
    if not log.is_file():
        print("  no log yet\n"); continue
    lines = [l for l in log.read_text().splitlines() if l and not l.startswith("#")]
    hdr = lines[0].split("\t")
    rows = [l.split("\t") for l in lines[1:] if l.split("\t")[0].isdigit()]
    if not rows:
        print("  no samples yet\n"); continue

    state = int(rows[-1][0])
    done = state >= TOTAL*0.999
    age = (time.time() - out.stat().st_mtime)/60 if out.exists() else None
    print(f"  {len(rows)} samples, last state {state:,} ({state/TOTAL:.1%})")
    print(f"  {'COMPLETE' if done else 'still running'}"
          + (f" — last write {age:.0f} min ago" if age is not None else ""))
    if not done and age is not None and age > 20:
        print("  !! no output for 20+ min — check it hasn't died")

    burn = len(rows)//10
    print(f"  (post 10% burn-in, {len(rows)-burn} samples)")
    for col in hdr:
        if any(k in col for k in ("posterior", "Tree.height", "ucldMean",
                                  "traitClockRate", "ucldStdev", "popSize")):
            i = hdr.index(col)
            try:
                vals = [float(r[i]) for r in rows[burn:]]
            except (ValueError, IndexError):
                continue
            e = ess_rough(vals)
            flag = "" if e >= 200 else "   <-- LOW"
            print(f"  {col:<34} mean {statistics.mean(vals):>12.5g}  ESS~{e:>6.0f}{flag}")

    for f in sorted(sd.glob("*")):
        if f.suffix in (".log", ".trees"):
            print(f"    {f.name:<36} {f.stat().st_size/1024:>9.1f} KB")
    print()

=== seed 12345 started Thu Aug 27 23:53:39 EDT 2026 ===
=== seed 12345 finished Fri Aug 28 08:08:56 EDT 2026 ===
=== seed 54321 started Fri Aug 28 08:08:56 EDT 2026 ===

--- seed12345 ---
  1001 samples, last state 100,000,000 (100.0%)
  COMPLETE — last write 177 min ago
  (post 10% burn-in, 901 samples)
  posterior                          mean      -9649.8  ESS~   438
  Tree.height                        mean       116.31  ESS~   346
  traitClockRate.host                mean     0.094357  ESS~   792
  popSize                            mean       141.52  ESS~   461
  ucldMean.H_clade_3_5state          mean   0.00052299  ESS~   494
  ucldStdev.H_clade_3_5state         mean      0.85048  ESS~   530
    clade3_5state.host.trees               14177.1 KB
    clade3_5state.log                        785.3 KB
    clade3_5state.trees                    15729.9 KB

--- seed54321 ---
  262 samples, last state 26,100,000 (26.1%)
  still running — last write 0 min ago
  (post 10% burn-in, 236 samples)
  posterior                          mean      -9653.2  ESS~   166   <-- LOW
  Tree.height                        mean       119.75  ESS~   147   <-- LOW
  traitClockRate.host                mean     0.092542  ESS~   236
  popSize                            mean       143.43  ESS~   179   <-- LOW
  ucldMean.H_clade_3_5state          mean   0.00050736  ESS~   148   <-- LOW
  ucldStdev.H_clade_3_5state         mean      0.84912  ESS~   203
    clade3_5state.host.trees                3719.6 KB
    clade3_5state.log                        222.3 KB
    clade3_5state.trees                     4125.5 KB